Add CLI testing utils
quarkus-qe/quarkus-test-framework pull request #1235
Opened 2024-08-01 11:56 UTC by mocenas

### Summary

Introduce QuarkusCLIUtils class. It contains supplementary methods for testing CLI apps. Like altering application's pom, properties file etc. 

Most of this works with physical files and requires QuarkusCliRestService.getFileFromApplication to work. That is why I put it in quarkus-test-cli module.

IMHO it is not worth it to write examples/test for this, since most of the methods are actually helpers to check something.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-08-01 13:40 UTC, gtroitsk commented
@mocenas did you tested it locally, probably as part of test development for quarkus update command?

2024-08-01 13:41 UTC, mocenas commented
> @mocenas did you tested it locally, probably as part of test development for quarkus update command?

Yes, this is tested locally. I already use it in development branch for quarkus update command.

2024-08-01 14:23 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static void writePropertiesToApp(QuarkusCliRestService app, Properties properties) throws IOException {
Maybe we can name it just `writeProperties`, because both this and `writePropertiesToYaml` method write props to app

2024-08-01 14:23 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static void writePropertiesToYaml(QuarkusCliRestService app, Properties properties) throws IOException {
If you have javadoc for `writePropertiesToApp`, please add the similar for this method

2024-08-01 14:23 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +     * Get dependencies for app's pom.
```suggestion
     * Get dependencies from app's pom.
```

2024-08-01 14:23 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        File pomfile = app.getFileFromApplication(subdir, "pom.xml");
Put `pom.xml` string to global vars please

2024-08-01 14:23 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        OutputStream output = new FileOutputStream(app.getFileFromApplication("pom.xml"));
Put `pom.xml` string to global vars please

2024-08-01 14:26 UTC, gtroitsk approved these changes
Thank you. I have requested only some small fixes.

2024-08-01 14:35 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static void writePropertiesToApp(QuarkusCliRestService app, Properties properties) throws IOException {
I don't like that. Because `writeProperties` might be confused to be complement for `getProperties` - which is reading `<properties>` tag from pom.xml. I would like to keep these with distinct names. And I though that name like `writePropertiesToProperties` is kind of bad.
Maybe would be better to rename both method to be `writePropertiesToProperties/YamlFile` ?

2024-08-01 14:37 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        File pomfile = app.getFileFromApplication(subdir, "pom.xml");
Does that really give a benefit? "pom.xml" is kind of a constant in maven world and I see no benefit for having `final String POM_XML="pom.xml"`.

2024-08-01 14:41 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static void writePropertiesToApp(QuarkusCliRestService app, Properties properties) throws IOException {
`writePropertiesToProperties/YamlFile` is good

2024-08-01 14:43 UTC, gtroitsk commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        File pomfile = app.getFileFromApplication(subdir, "pom.xml");
It makes sense only in the point of using the same value in some places

2024-08-01 14:43 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +     * Get dependencies for app's pom.
done.

2024-08-01 14:51 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        File pomfile = app.getFileFromApplication(subdir, "pom.xml");
It is true that I have some other "well known" strings/filenames in constants so I can add pom to them.
done.

2024-08-01 14:52 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        OutputStream output = new FileOutputStream(app.getFileFromApplication("pom.xml"));
done

2024-08-01 14:52 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static void writePropertiesToApp(QuarkusCliRestService app, Properties properties) throws IOException {
done

2024-08-01 14:52 UTC, mocenas commented
To whoever will be merging this. Please don't forget to squash the commits.

2024-08-01 14:53 UTC, mocenas commented
> Thank you. I have requested only some small fixes.

Done, also I've added few additional comments.

2024-08-01 15:02 UTC, merged

2024-08-01 15:20 UTC, jedla97 requested changes
Overal it's look good. Just have one change from my side and question about yaml.

2024-08-02 07:14 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +            writer.append("\n");
YAML has benevolent syntax. The usually used one is the one you wrote here. But `quarkus.log.level: DEBUG` is also possible.

2024-08-02 07:40 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +        return loadPropertiesFromFile(getPropertiesYamlFile(app));
Unfortunately you're right :-(. Properties.load cannot really go through yaml. I will fix this to actually parse it.

2024-08-02 07:40 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +    public static final String RESOURCES_DIR = "src/main/resources";
OK I will change it.

2024-08-02 08:57 UTC, mocenas commented on quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
> +            writer.append("\n");
But for complex yaml, this doesn't work, so I'm fixing this one also.

2024-08-02 08:59 UTC, mocenas commented
Since this PR is already merged I fixed the issues in #1236.
Thanks @jedla97 for spotting those.