Support gRPC TLS communication and TLS registry
quarkus-qe/quarkus-test-framework pull request #1272
Opened 2024-09-02 17:28 UTC by michalvavrik

### Summary

- Adds support for gRPC running on same Vert.X HTTP server (which shall be primary Quarkus way in the future, not using separate one).
- Closes: #1048
- Adds support for TLS and mTLS communication with gRPC service
- Integrates TLS registry support
- Changed channel return type to `ManagedChannel` for looking at upstream test coverage, they often shutdown after using stubs and I wonder if we shouldn't do it as well for baremetal tests (I remember something Fedor said about OpenShift tests that makes me thing it shouldn't be automatic).

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-09-02 21:34 UTC, michalvavrik commented
Issues on Windows are related to escaping, I don't know if I fixed them as obviously I didn't try it (it's bit late...). If it's red tomorrow, I'll work around that, but it's a small thing, I think you can freely comment on changes. Thanks

2024-09-02 21:56 UTC, michalvavrik commented
Interesting, Quarkus turns `-Dquarkus.tls.grpc-tls.trust-store.pem.certs="C:\Users\RUNNER~1\AppData\Local\Temp\quarkus-qe-certs809756706346777605\quarkus-qe-server-ca.crt"` into:

```
2024-09-02T21:43:49.8846143Z 21:43:49,799 INFO  [app] Caused by: java.nio.file.NoSuchFileException: C:UsersRUNNER~1AppDataLocalTempquarkus-qe-certs809756706346777605quarkus-qe-server-ca.crt
2024-09-02T21:43:49.8847380Z 21:43:49,799 INFO  [app] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
2024-09-02T21:43:49.8848370Z 21:43:49,799 INFO  [app] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
2024-09-02T21:43:49.8849385Z 21:43:49,799 INFO  [app] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
2024-09-02T21:43:49.8850459Z 21:43:49,799 INFO  [app] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
2024-09-02T21:43:49.8851372Z 21:43:49,799 INFO  [app] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
2024-09-02T21:43:49.8852109Z 21:43:49,799 INFO  [app] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
2024-09-02T21:43:49.8852987Z 21:43:49,799 INFO  [app] 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
2024-09-02T21:43:49.8853880Z 21:43:49,799 INFO  [app] 	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
2024-09-02T21:43:49.8854673Z 21:43:49,799 INFO  [app] 	at io.quarkus.tls.runtime.config.TlsConfigUtils.read(TlsConfigUtils.java:43)
2024-09-02T21:43:49.8855286Z 21:43:49,799 INFO  [app] 	... 20 more
```
I'll play with it tomorrow.

2024-09-03 07:48 UTC, michalvavrik commented
Starting experiments on Windows, will report back when I fix it.

2024-09-03 09:43 UTC, michalvavrik commented
I have doubled backslashes for my use case, which fixed the issue. I think we need to do it for everywhere https://github.com/quarkus-qe/quarkus-test-framework/issues/1275 but I do not there to do this in here. I am in hurry and don't have time to fix/debug side-effects in backports etc.

2024-09-03 10:13 UTC, fedinskiy requested changes
We need a couple of small changes.

And what about Openshift? Will it work there?

2024-09-03 10:13 UTC, fedinskiy commented on quarkus-test-service-grpc/src/main/java/io/quarkus/test/bootstrap/GrpcService.java
> +            throw new IllegalStateException("TLS support for separate gRPC server is currently not supported");
```suggestion
            throw new IllegalStateException("TLS is not currently supported for a separate gRPC server");
```

2024-09-03 10:13 UTC, fedinskiy commented on quarkus-test-service-grpc/src/main/java/io/quarkus/test/bootstrap/GrpcService.java
> +            throw new IllegalStateException("Exactly one certificate must exist for the SSL configuration to work");
We should mention, which property we used to look for a certificate  in the error message. And a number of found certificates

2024-09-03 10:13 UTC, fedinskiy commented on examples/grpc/src/test/java/io/quarkus/qe/grpc/GrpcMtlsTlsRegistryIT.java
> +    @QuarkusApplication(grpc = true, ssl = true, certificates = @Certificate(format = PEM, configureHttpServer = true, configureKeystore = true, configureTruststore = true, tlsConfigName = "grpc-tls"
As far as I understand, `CN=Hagrid` is now included in certificates. Please, add the scripts you used to generate them

2024-09-03 10:26 UTC, michalvavrik commented
> And what about Openshift? Will it work there?

https://github.com/quarkus-qe/quarkus-test-framework/issues/1053 IIRC you cannot have both enabled HTTP2 and HTTP1 in OpenShift cluster. Things might have changed, but it's beyond what I can do ATM.

2024-09-03 10:31 UTC, michalvavrik commented on quarkus-test-service-grpc/src/main/java/io/quarkus/test/bootstrap/GrpcService.java
> +            throw new IllegalStateException("Exactly one certificate must exist for the SSL configuration to work");
will do

2024-09-03 10:32 UTC, michalvavrik commented on examples/grpc/src/test/java/io/quarkus/qe/grpc/GrpcMtlsTlsRegistryIT.java
> +    @QuarkusApplication(grpc = true, ssl = true, certificates = @Certificate(format = PEM, configureHttpServer = true, configureKeystore = true, configureTruststore = true, tlsConfigName = "grpc-tls"
> As far as I understand, CN=Hagrid is now included in certificates. Please, add the scripts you used to generate them

yeah, you can see that `SecurityIdentity` is not anonymous and its principal contains DN with `CN=Hagrid` which is then asserted in `HiReply`. therefore authentication is verified and so is certificates value

2024-09-03 12:43 UTC, fedinskiy approved these changes

2024-09-03 12:43 UTC, merged