Fix the Keycloak memory issue on Podman setting JAVA_OPTS_APPEND
quarkus-qe/quarkus-test-framework pull request #1389
Opened 2024-10-30 11:38 UTC by jcarranzan

### Summary
This PR addresses the issue https://github.com/quarkus-qe/quarkus-test-suite/issues/2106 
where Podman environments were unable to correctly enforce memory limits for Keycloak containers. The solution applies a conditional setting for environments using Podman by adding ` container.withEnv("JAVA_OPTS_APPEND", "-XX:MaxRAM=1g");`, ensuring that the Java heap memory allocation respects the 1GB limit in these environments.

It won' be necessary this https://github.com/quarkus-qe/quarkus-test-suite/pull/2125/files in test suite.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-10-30 12:21 UTC, mabartos reviewed
@jcarranzan Thanks for the PR!

If it's verified the container limit set via the testcontainer's `withMemory()` does not work with Podman, but does with Docker, we can go this direction.

As a temporary solution, it works for me as well, but it'd be good to verify whether setting the limit really works with Docker and is not opinionated by available memory on the agent (Docker 16GB vs Podman 8GB).

2024-10-30 12:21 UTC, mabartos commented on quarkus-test-service-keycloak/src/main/java/io/quarkus/test/services/containers/KeycloakGenericDockerContainerManagedResource.java
> +            container.withEnv("JAVA_OPTS_APPEND", "-XX:MaxRAM=1g");
```suggestion
            container.withEnv("JAVA_OPTS_APPEND", String.format("-XX:MaxRAM=%sm", model.getMemoryLimitMiB()));
```

2024-10-30 13:45 UTC, rsvoboda requested changes
I was expecting JAVA_OPTS_APPEND approach to be applied always, no matter if it's podman or docker. Can you elaborate why did you pick if-else approach?

2024-10-30 13:45 UTC, rsvoboda commented on quarkus-test-service-keycloak/src/main/java/io/quarkus/test/services/containers/KeycloakGenericDockerContainerManagedResource.java
>                  .ifPresent(config -> config.withMemory(convertMiBtoBytes(model.getMemoryLimitMiB()))));
Same as line 60-61

2024-10-30 13:55 UTC, jcarranzan commented on quarkus-test-service-keycloak/src/main/java/io/quarkus/test/services/containers/KeycloakGenericDockerContainerManagedResource.java
>                  .ifPresent(config -> config.withMemory(convertMiBtoBytes(model.getMemoryLimitMiB()))));
Oh I forgot to remove redundant lines after the else, srry.
I've choosed the` if else statement` because this issue just happens with Podman jobs and there are no issues on docker jobs.

2024-10-30 14:10 UTC, mabartos commented on quarkus-test-service-keycloak/src/main/java/io/quarkus/test/services/containers/KeycloakGenericDockerContainerManagedResource.java
>                  .ifPresent(config -> config.withMemory(convertMiBtoBytes(model.getMemoryLimitMiB()))));
If there's really a difference between Docker/Podman, both work for me and I leave the decision up to you @jcarranzan @rsvoboda.

Perhaps, I'd incline more to use the `MaxRAM` as @rsvoboda suggested to simplify things and have a unified approach for it.

2024-10-30 14:52 UTC, jcarranzan commented on quarkus-test-service-keycloak/src/main/java/io/quarkus/test/services/containers/KeycloakGenericDockerContainerManagedResource.java
>                  .ifPresent(config -> config.withMemory(convertMiBtoBytes(model.getMemoryLimitMiB()))));
Ok I'll keep JAVA_OPTS_APPEND approach always as @rsvoboda suggested, thanks!

2024-10-30 15:00 UTC, mabartos reviewed
@jcarranzan LGTM. I hope the `JAVA_OPTS_APPEND` is not set somewhere else. Please, let me know if it works as expected.

2024-10-31 07:43 UTC, jcarranzan commented
> `JAVA_OPTS_APPEND`

Yes, it worked when I tested it on the Jenkins Podman job. 
As I mentioned above in the description, once this MR is merged, we should just remove this property : 
https://github.com/quarkus-qe/quarkus-test-suite/blob/27e6dbcb22319e740a3c065ee7d748053ea61f23/http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java#L20

2024-10-31 09:28 UTC, rsvoboda approved these changes

2024-10-31 09:28 UTC, merged

2024-10-31 09:29 UTC, rsvoboda commented
@jcarranzan if this is intended for backport, please set appropriate label