Apply idea code analysis suggestions
quarkus-qe/quarkus-test-framework pull request #1406
Opened 2024-11-14 00:14 UTC by gtroitsk

### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-11-14 00:15 UTC, gtroitsk commented
run tests

2024-11-14 14:23 UTC, gtroitsk commented
run tests

2024-11-14 14:36 UTC, mocenas requested changes
Most changes are OK. But some needs to be reverted.

2024-11-15 08:34 UTC, gtroitsk commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +            String label = String.format("%s=%s", KubectlClient.LABEL_SCENARIO_ID, labelValue);
It's a private method that is used for delete resources in current namespace. labelName is const for service, it will not change. If I am wrong, please give me an example where it will be a problem

2024-11-15 08:43 UTC, gtroitsk commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> -
I will revert it, we should change all this methods in TS in the future, that's not much

2024-11-15 09:34 UTC, mocenas commented on quarkus-test-openshift/pom.xml
> +            <!--  Excludes artifact from CVE-2023-0833  -->
OK since this shouldn't break anything, I'm OK with it.

2024-11-15 09:46 UTC, mocenas commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +            String label = String.format("%s=%s", KubectlClient.LABEL_SCENARIO_ID, labelValue);
You're probably right, that it this case, there is not need to have a variable labelName. Lets go with this change.

2024-11-15 09:46 UTC, mocenas commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            String label = String.format("%s=%s", OpenShiftClient.LABEL_SCENARIO_ID, labelValue);
Explained above, lets go with this change.

2024-11-15 10:14 UTC, gtroitsk commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusMavenPluginBuildHelper.java
> +    private static String getNewPomToParentDirPath(Path newPomDir, Node parentChildNode) {
Reverted

2024-11-15 10:14 UTC, gtroitsk commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusMavenPluginBuildHelper.java
> +    private static Path getNewDir(Path appFilePath, String normalizedTestSourceDirPath, Path srcMainJava) {
Reverted

2024-11-15 10:55 UTC, gtroitsk commented on quarkus-test-openshift/pom.xml
> +            <!--  Excludes artifact from CVE-2023-0833  -->
As I wrote above, there is problem with `GrpcWebSocketListener` in TS. This class is not used in any test cases, when we remove it, we are safe. I run tests in `http-advanced-*` modules with FW snapshot and all passed.

2024-11-15 11:02 UTC, gtroitsk commented
run tests

2024-11-15 12:28 UTC, mocenas commented on quarkus-test-openshift/pom.xml
> +            <!--  Excludes artifact from CVE-2023-0833  -->
`GrpcWebSocketListener`s are removed in https://github.com/quarkus-qe/quarkus-test-suite/pull/2199 so no need to worry about them.

2024-11-15 12:44 UTC, mocenas approved these changes
LGTM. Let's wait for OCP CI.

2024-11-15 15:24 UTC, merged