Add Quarkus test framework metrics
quarkus-qe/quarkus-test-framework pull request #157
Opened 2021-07-23 14:57 UTC by pjgg

- Support the ability to emit prometheus metrics
- Add the following metrics:
   - `ts_quarkus_gauge_requests_total` represent the total amount of test
   - `ts_quarkus_gauge_requests_success` represent the total amount of succeed test
   - `ts_quarkus_gauge_requests_ignore` represent the total amount of ignored test
   - `ts_quarkus_gauge_requests_fail` represent the total amount of failures 
   - `ts_quarkus_gauge_modules` represents metrics associated to the test modules. You will have one of this metrics per quarkus scenario / module.
        - `ts_quarkus_module_name` represents the maven modules name
        - `ts_quarkus_module_status` could be `module_success` or `module_fail`
   - `ts_quarkus_histogram_modules_duration`

2021-07-26 08:22 UTC, Sgitario requested changes
Apart from my comments, the PR failed when using 2.1.0.Final, can you check?

2021-07-26 08:22 UTC, Sgitario commented on examples/metrics-extension/src/test/java/io/quarkus/qe/MetricsExtensionBootstrapIT.java
> +    static RestService app = new RestService();
Doing this is not necessary anylonger. You can skip doing this and RestAssured will be already configured by you.

2021-07-26 08:22 UTC, Sgitario commented on examples/metrics-extension/src/test/java/io/quarkus/qe/MetricsExtensionBootstrapIT.java
> +                .statusCode(200)
Use HttpStatus.SC_OK.

2021-07-26 08:22 UTC, Sgitario commented on examples/metrics-extension/src/test/java/io/quarkus/qe/MetricsExtensionBootstrapIT.java
> +    private void WhenRetrieveMetrics(String metricId) {
The method starts with When instead of when.

2021-07-26 08:22 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/ExtensionBootstrap.java
> +    default void onIgnore(ExtensionContext context, Optional<String> reason) {
I prefer onTestDisabled or onDisabled. Ignore can mean other things...

2021-07-26 08:22 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/metrics/MetricsExtensionBootstrap.java
> +    private static final String DEFAULT_PROMETHEUS_ENDPOINT_VALUE = "127.0.0.1:9091";
Instead of providing a default prometheus endpoint, I think it's better to disable this feature if the `ts.prometheus-http-endpoint` is not provided.

2021-07-26 08:22 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/metrics/QuarkusLabels.java
> +        quarkusPluginVersion = new PropertyLookup("quarkus-plugin.version", DEFAULT_VERSION_NUMBER).get();
We should use Version.getVersion() (from import io.quarkus.builder.Version).

2021-07-28 17:41 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/metrics/MetricsExtensionBootstrap.java
> +    private static final String DEFAULT_PROMETHEUS_ENDPOINT_VALUE = "127.0.0.1:9091";
If `ts.prometheus-http-endpoint` is not set then this extension is disabled.

2021-07-29 06:54 UTC, Sgitario requested changes
Besides the system properties, the rest of the changes look ok to me.

2021-07-29 06:54 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/QuarkusScenarioBootstrap.java
> +                System.setProperty(systemProperty.name(), systemProperty.value());
-100 
Doing System.setProperty may affect other tests as you're changing a system property...

2021-07-29 07:30 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/QuarkusScenarioBootstrap.java
> +                System.setProperty(systemProperty.name(), systemProperty.value());
A global system property manipulation is not threadsafe so we decide to don't include this feature. 

If `ts.prometheus-http-endpoint` is not defined then metrics are disabled.

2021-07-29 07:34 UTC, Sgitario reviewed
Just a nitpick enhancement.

2021-07-29 07:34 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/metrics/MetricsExtensionBootstrap.java
> +        return context.getRequiredTestClass().isAnnotationPresent(QuarkusScenario.class);
Changing this line to: 
```
return extensionEnabled && context.getRequiredTestClass().isAnnotationPresent(QuarkusScenario.class);
```

Makes the rest of methods not need to check for the `extensionEnabled` flag

2021-07-29 07:41 UTC, Sgitario approved these changes

2021-07-29 08:23 UTC, Sgitario commented
The windows failure in JVM works fine locally. 
Merging

2021-07-29 08:23 UTC, merged