Enable run your test without ephemeral namespaces
quarkus-qe/quarkus-test-framework pull request #188
Opened 2021-08-06 15:28 UTC by pjgg

- Disable ephemeral namespaces

Most of the time ephemeral namespace is a good idea, but some other times is not possible because maybe you are 
not allowed to create namespaces on the fly with your own user. In those cases, you can disable ephemeral namespaces 
and run all your test in your current namespace.

`-Dts.openshift.ephemeral.namespaces.enabled=false`

Full example command: `mvn clean verify -Popenshift -Dts.openshift.ephemeral.namespaces.enabled=false`

2021-08-09 05:47 UTC, Sgitario requested changes
The same comments from Kubernetes' changes apply also to OpenShift's changes.
In general:
- The label ID is using a timestamp that might not be unique. Use the test class name instead.
- We don't need to update the templates but add the label in the `enrichTemplate` method only (as it has already been done).
- The current solution does not work when adding custom resources in Operators (as it would require users to manually add the label).
- Move the logic of create/delete resources from the K8s/OCP API clients to the bootstrap, so we prevent users from using this logic.

Moreover, I'm a bit reluctant to:
- Support this feature as it embraces a testing bad practice. An environment must be repeatable and reproducible and we can't guarantee that all the resources will be cleared out (see custom resources or resources that users will create as part of the test scenario). Still, I see benefit though.
- Keep adding new features on the test framework when we didn't run a fully green execution of our test suite (even for JVM and Native). Even more, we don't have an OCP environment stable to verify the test framework yet. 

I would like to open the discussion to @rsvoboda and @mjurc too.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +    private static final String K8S_LABEL_TO_WATCH_FOR_LOGS = "tsLogWatch";
Why adding a `K8S_` prefix in this field? I think taking into account that this is in the KubectlClient, we don't need it.
Also, group the label fields together.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +    private KubectlClient(boolean ephemeralNamespaceEnabled) {
Having boolean parameters to do one or another thing is generally a bad practice. Moreover, maybe this logic should be now in KubernetesExtensionBootstrap.java.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +    public void deleteResourcesByLabel(String labelName, String labelValue) {
I think this method should not be opened in the KubectlClient API (this API is open to be used for users).

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +        return "" + System.currentTimeMillis();
This might return a different ID for the same test resources... 
Please, use the test class name instead.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/services/containers/KubernetesContainerManagedResource.java
> +                .replaceAll(quote("${TEST_CASE_NAME}"), "" + client.getScenarioId());
Why do we need to do this? You're already adding the label in `enrichTemplate`.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/services/quarkus/KubernetesQuarkusApplicationManagedResource.java
> +                .replaceAll(quote("${TEST_CASE_NAME}"), client.getScenarioId());
Why do we need to do this? You're already adding the label in `enrichTemplate`.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/resources/kubernetes-deployment-template.yml
> +      scenarioId: "${TEST_CASE_NAME}"
Why do we need to do this? You're already adding the label in `enrichTemplate`.

2021-08-09 05:47 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/resources/kubernetes-deployment-template.yml
> +          scenarioId: "${TEST_CASE_NAME}"
Why do we need to do this? You're already adding the label in `enrichTemplate`.

2021-08-09 05:47 UTC, Sgitario commented on README.md
> +`-Dts.openshift.ephemeral.namespaces.enabled=false`
Add a note about the K8s property too.

2021-08-10 05:49 UTC, Sgitario requested changes
- Labels are being overwritten by the scenario ID label
- To get the active namespace: the command `oc project -q` is not working for me when using OCP 4.8 (not sure if it's an intermittent issue or not). But there is a much easier way to get the active namespace: `return new DefaultOpenShiftClient().getNamespace();` and as far I see, it's working consistently.
- The OpenShift extension deployment strategy is not adding the scenario label and hence is not being removed.
- The operators are not being deleted either.

2021-08-10 05:49 UTC, Sgitario commented on README.md
> +* Ocp:
```suggestion
* OpenShift: 
```

2021-08-10 05:49 UTC, Sgitario commented on README.md
> +* K8s:
```suggestion
* Kubernetes:
```

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +            obj.getMetadata().setLabels(Map.of(LABEL_SCENARIO_ID, getScenarioId()));
If the metadata had labels already, using `setLabels` would overwrite it.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            obj.getMetadata().setLabels(Map.of(LABEL_SCENARIO_ID, getScenarioId()));
If the metadata had labels already, using `setLabels` would overwrite it.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/ExtensionOpenShiftQuarkusApplicationManagedResource.java
> +
???

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +        List<String> namespaceOutputResp = new ArrayList<>();
There is a much easier way to get the current namespace: `return new DefaultOpenShiftClient().getNamespace();`

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +        currentNamespace = (ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) ? createNamespace() : findActiveNamespace();
There is extra paranthesis here.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        currentNamespace = (ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) ? createProject() : findActiveNamespace();
There is extra paranthesis here.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        deleteResourcesByLabel(LABEL_SCENARIO_ID, getScenarioId());
If ephemeral is active, this is not necessary. Let's remove the resources by label only if ephemeral is disabled.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        List<String> namespaceOutputResp = new ArrayList<>();
The command `oc project -q` is not working for me when using OCP 4.8 (not sure if it's an intermittent issue or not). But there is a much easier way to get the active namespace: `return new DefaultOpenShiftClient().getNamespace();` and as far I see, it's working consistently.

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +    public String getScenarioId() {
this should be private

2021-08-10 05:49 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +        deleteResourcesByLabel(LABEL_SCENARIO_ID, getScenarioId());
We should only delete resources by label when the ephemeral namespaces flag is disabled.

2021-08-16 05:36 UTC, Sgitario requested changes
The only missing important bit are:
- The OpenShift extension deployment strategy is not adding the scenario label and hence is not being removed.
- Operators are not being uninstalled
- Custom Resources (for operators) are not being uninstalled either

For the operators example, please try with `OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT` scenario for example to double check everything is cleared out.

2021-08-16 05:36 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/ExtensionOpenShiftQuarkusApplicationManagedResource.java
> +        //   args.add(withLabelsForscenarioId());
We should add the labels to the Quarkus OpenShift extension, otherwise it won't work for this deployment strategy.

2021-08-16 05:36 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            new Command(OC, "delete", "-n", client.getNamespace(), "all", "-l", label).runAndWait();
I think it's safer to use `currentNamespace` instead of `client.getNamespace()`

2021-08-16 05:36 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                new Command(OC, "delete", "project", client.getNamespace()).runAndWait();
I think it's safer to use `currentNamespace` instead of `client.getNamespace()`

2021-08-16 05:36 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +            new Command(KUBECTL, "delete", "-n", client.getNamespace(), "all", "-l", label).runAndWait();
I think it's safer to use `currentNamespace` instead of `client.getNamespace()`

2021-08-16 17:20 UTC, pjgg commented
This feature doesn't support Operators.

2021-08-17 06:15 UTC, Sgitario requested changes
Some leftover and one minor change (about the comment).
Once updated, I think we can proceed with the test on OCP.

2021-08-17 06:15 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +    private static final int KUBECTL_CMD_TIMEOUT_SEC = 5;
This field is not used.

2021-08-17 06:15 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/inject/KubectlClient.java
> +    private final Pattern namespaceRegexp = Pattern.compile(".*namespace.*");
This field is not used.

2021-08-17 06:15 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
>                  // add label for logs
Update comment to reflect the new behaviour

2021-08-18 13:32 UTC, Sgitario commented
run tests

2021-08-19 05:19 UTC, Sgitario commented
run tests - with ephemeral namespaces disabled.

2021-08-19 05:22 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +        client = KubectlClient.create(generateScenarioId(context));
To be refactored in https://github.com/quarkus-qe/quarkus-test-framework/issues/209

2021-08-19 05:22 UTC, Sgitario approved these changes
Let's wait for the CI before merging

2021-08-19 05:57 UTC, Sgitario commented
run tests

2021-08-19 07:20 UTC, Sgitario commented
run tests

2021-08-19 07:29 UTC, Sgitario commented
run tests

2021-08-19 08:30 UTC, Sgitario requested changes
Failed the OCP jobs due that some services generated by serverless are not cleaned up and hence doing the following scenarios to fail because the route host is already claimed:

```
oc: route/app not accepted: HostAlreadyClaimed (svc/app)
```

2021-09-06 12:50 UTC, Sgitario requested changes
Remove leftovers in the OCP and K8S extension bootstraps.

2021-09-06 17:40 UTC, Sgitario approved these changes

2021-09-06 17:40 UTC, merged