Add reactive webclient service
quarkus-qe/quarkus-test-framework pull request #207
Opened 2021-08-17 05:38 UTC by Sgitario

We will use the Vert.x Munity webclient implementation
These changes are being covered in the Greetings example and in OpenShift and K8s.

2021-08-17 05:38 UTC, Sgitario commented on quarkus-test-core/pom.xml
> +            <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
@pjgg do you foresee any side effects of adding this dependency?

2021-08-17 15:04 UTC, pjgg commented on quarkus-test-core/pom.xml
> +            <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
No problem at all

2021-08-17 15:48 UTC, pjgg requested changes

2021-08-17 15:48 UTC, pjgg commented on examples/greetings/src/main/java/io/quarkus/qe/GreetingResource.java
> +@Blocking
`@Blocking` is not really necessary if you return `T` or `void` .

2021-08-17 15:48 UTC, pjgg commented on examples/greetings/src/test/java/io/quarkus/qe/ReactiveGreetingResourceIT.java
> +    }
instead of swap from non-blocking to blocking we could also test it in a reactive way:

````
@QuarkusScenario
public class ReactiveGreetingResourceIT {

    @QuarkusApplication
    static final ReactiveWebClientService app = new ReactiveWebClientService();

    @Test
    public void shouldSayDefaultValue() {

        UniAssertSubscriber<String> subscriber = app.webClient().get("/reactive-greeting")
                .expect(ResponsePredicate.status(HttpURLConnection.HTTP_OK))
                .send()
                .map(HttpResponse::bodyAsString)
                .subscribe().withSubscriber(UniAssertSubscriber.create());

        subscriber.awaitItem(Duration.ofSeconds(10))
                .assertCompleted()
                .assertItem("Hello, I'm victor");
    }
}
````

2021-08-17 15:48 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/ReactiveWebClientService.java
> +public class ReactiveWebClientService extends BaseService<ReactiveWebClientService> {
What about renaming the service. I mean, is reactive that is true but could be RxJava, or `callback-hell` or...Mutiny!
By this way would be more aligned to the `RestService`

In my opinion, I will rename this class to `RestMutinyService` but also I will rename `RestService` to `RestAssuranceService`. 

Why `RestMutinyService` ?, we are using under the hood vertx that is true, but vertx has a lot of flavors, so ReactiveWebClient is too open... we are talking about Vertx futures, rxJava, Mutiny... ? 

And I think that `RestService` could be renamed to `RestAssuranceService` following the same principle. 

On the other hand (going back to `ReactiveWebClientService` class) I think that we could rename the method `webClient` by `intance`

Something like this: 

```
public class RestMutinyService extends BaseService<RestMutinyService> {

    private WebClientOptions webClientOptions = new WebClientOptions();
    private WebClient webClient;

    public RestMutinyService withWebClientOptions(WebClientOptions options) {
        this.webClientOptions = options;
        return this;
    }

    @Override
    public void start() {
        super.start();

        webClient = WebClient.create(Vertx.vertx(), webClientOptions
                .setDefaultHost(getHost().replace("http://", StringUtils.EMPTY))
                .setDefaultPort(getPort()));
    }

    public WebClient instance() {
        return webClient;
    }
}

```


And then could be used by this way:

```

@QuarkusScenario
public class ReactiveGreetingResourceIT {

    @QuarkusApplication
    static final RestMutinyService app = new RestMutinyService();

    @Test
    public void shouldSayDefaultValue() {

        UniAssertSubscriber<String> subscriber = app.instance().get("/reactive-greeting")
                .expect(ResponsePredicate.status(HttpURLConnection.HTTP_OK))
                .send()
                .map(HttpResponse::bodyAsString)
                .subscribe().withSubscriber(UniAssertSubscriber.create());

        subscriber.awaitItem(Duration.ofSeconds(10))
                .assertCompleted()
                .assertItem("Hello, I'm victor");
    }
}

```

2021-08-18 05:15 UTC, Sgitario commented on examples/greetings/src/main/java/io/quarkus/qe/GreetingResource.java
> +@Blocking
Yes, I know, but I wanted to explicitly say that it was blocking.
Anyway, I'm going to remove it to avoid misconceptions.

2021-08-18 05:18 UTC, Sgitario commented on examples/greetings/src/test/java/io/quarkus/qe/ReactiveGreetingResourceIT.java
> +    }
I see the reactive way much more complicated than the blocking way, but I've changed following your suggestion.

2021-08-18 05:25 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/ReactiveWebClientService.java
> +public class ReactiveWebClientService extends BaseService<ReactiveWebClientService> {
I don't like to rename `webClient` to `instance`, the final usage would be a bit odd: `app.instance()...`.
However I think you made a good point about the REST service implementations, but what about easing this by removing the new service called `ReactiveWebClientService` and moving the `WebClient` stuff to the existing RestService? 
This way in RestService we have the blocking approach (RestAssured) and the reactive way (using Vert.x Mutiny client) to interact with our services.
I've made this change already, so looking forward to hearing from you.

2021-08-18 06:15 UTC, Sgitario commented on examples/greetings/src/test/java/io/quarkus/qe/ReactiveGreetingResourceIT.java
> +    }
The reactive way is failing for Quarkus 1.13.7.Final (the mutiny API has changed).
I will keep using the original approach.

2021-08-18 15:18 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RestService.java
> +    public WebClient mutiny(WebClientOptions options) {
brilliant!, too much better by this way!

2021-08-18 15:18 UTC, pjgg approved these changes

2021-08-18 15:18 UTC, merged