Refactor solution for Metrics ++ Polish properties
quarkus-qe/quarkus-test-framework pull request #221
Opened 2021-08-25 09:24 UTC by Sgitario

The changes in this PR are:
- Change the tracing/metrics format to follow the same format as the rest of the properties

This change allows to enable/disable/configure these extensions per module.

- Refactor the metrics module to decouple the metrics of prometheus and have another type of exporter: file.

My idea is to integrate the metrics within the running Quarkus application, so we can assert metrics during the test execution without needing to have a Prometheus.

Also, we're exporting the metrics into a file (/target/logs/metrics.out).

2021-08-31 12:17 UTC, pjgg requested changes

2021-08-31 12:17 UTC, pjgg commented on misc/Metrics.md
> +   - `module_name` represents the maven modules name
Currently, the module name is the project root folder. The problem is that, If we have tree scenarios we will have tree moduleNames with the same name, and that is not very useful. What about replace `module_name` by `scenario_name` where scenario name is `rootFolderName_testClassName`

2021-08-31 12:17 UTC, pjgg commented on misc/Metrics.md
> +   - `tests_success` represent the total amount of succeed test
what about... test_successed?

2021-08-31 12:17 UTC, pjgg commented on misc/Metrics.md
> +   - `tests_total` represent the total amount of test
tests_amount?

2021-08-31 12:17 UTC, pjgg commented on misc/Metrics.md
> +   - `tests_fail` represent the total amount of failures
tests_failed?

2021-09-01 05:53 UTC, Sgitario commented on misc/Metrics.md
> +   - `module_name` represents the maven modules name
+1

2021-09-01 06:04 UTC, Sgitario commented on misc/Metrics.md
> +   - `module_name` represents the maven modules name
I kept the `module_name` and added a new one only for the scenario name `scenario_name` (for `testClassName`). 
Let me know if it looks better now.

2021-09-01 06:04 UTC, Sgitario commented on misc/Metrics.md
> +   - `tests_fail` represent the total amount of failures
+1

2021-09-01 06:04 UTC, Sgitario commented on misc/Metrics.md
> +   - `tests_success` represent the total amount of succeed test
+1

2021-09-01 06:05 UTC, Sgitario commented on misc/Metrics.md
> +   - `tests_total` represent the total amount of test
I prefer either `total` or `count`, wdyt?

2021-09-01 06:23 UTC, Sgitario commented
@pjgg I've already addressed all your comments:
- `module_name` remains the same, but I've added an additional label `scenario_name` with the running class name
- renamed `module_duration_seconds` to `scenario_duration_seconds`
- renamed all the metrics from `success` to `succeed` and `fail` to `failed`

2021-09-01 06:56 UTC, pjgg approved these changes

2021-09-01 07:04 UTC, merged