Support Remote Dev testing
quarkus-qe/quarkus-test-framework pull request #231
Opened 2021-09-02 13:43 UTC by Sgitario

The test framework supports the Remote DEV mode in Quarkus for baremetal, OpenShift and Kubernetes. 
Basically, we can deploy a Quarkus application in Remote DEV and after applying changes in the source code, these changes
will be automatically deployed in the running application.

```java
@QuarkusScenario
public class RemoteDevGreetingResourceIT {

    static final String VICTOR_NAME = "victor";

    static final String HELLO_IN_ENGLISH = "Hello";
    static final String HELLO_IN_SPANISH = "Hola";

    @RemoteDevModeQuarkusApplication
    static RemoteDevModeQuarkusService app = new RemoteDevModeQuarkusService();

    @Test
    public void shouldUpdateResourcesAndSources() {
        // Should say first Victor (the default name)
        app.given().get("/greeting").then().statusCode(HttpStatus.SC_OK).body(is(HELLO_IN_ENGLISH + ", I'm " + VICTOR_NAME));

        // Modify default name to manuel
        app.modifyFile("src/main/java/io/quarkus/qe/GreetingResource.java",
                content -> content.replace(HELLO_IN_ENGLISH, HELLO_IN_SPANISH));

        // Now, the app should say Manuel
        AwaitilityUtils.untilAsserted(
                () -> app.given().get("/greeting").then().statusCode(HttpStatus.SC_OK)
                        .body(is(HELLO_IN_SPANISH + ", I'm " + VICTOR_NAME)));
    }
}
```

2021-09-02 13:43 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/DevModeQuarkusService.java
> -    private static void sleep(int millis) {
This was a leftover.

2021-09-02 14:46 UTC, rsvoboda requested changes

2021-09-02 14:46 UTC, rsvoboda commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RemoteDevModeQuarkusService.java
> +    public void modifyFile(String file, Function<String, String> modifier) {
`modifyFile` and `copyFile` are imho the same as in DevModeQuarkusService

2021-09-02 14:46 UTC, rsvoboda commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/DevModeQuarkusService.java
> +public class DevModeQuarkusService extends RemoteDevModeQuarkusService {
Not sure if we need / want this. What's the motivation to extend RemoteDevModeQuarkusService.

To me the natural flow would be that RemoteDevMode extends DevMode.

2021-09-02 14:46 UTC, rsvoboda commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RemoteDevModeQuarkusService.java
> +    }
`public WebClient webClient() {` is not available intentionally ?

2021-09-03 04:46 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/DevModeQuarkusService.java
> +public class DevModeQuarkusService extends RemoteDevModeQuarkusService {
Ops, this was a leftover.
Reverting.

2021-09-03 04:49 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RemoteDevModeQuarkusService.java
> +    public void modifyFile(String file, Function<String, String> modifier) {
What I'm going to do is to remove the RemoteDevModeQuarkusService. For RemoteDev, we should still use the existing DevModeQuarkusService.
I didn't do this initially because remote dev didn't have dev ui, but I don't think we need to be very precise on this.

2021-09-03 04:50 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RemoteDevModeQuarkusService.java
> +    }
RemoteDevModeQuarkusService has been deleted.

2021-09-03 04:54 UTC, Sgitario commented
@rsvoboda I've removed the RemoteDevModeQuarkusService, so for this mode, users would need to use DevModeQuarkusService.

2021-09-06 12:58 UTC, mjurc approved these changes
LGTM!

2021-09-06 12:58 UTC, merged