Quarkus source S2I strategy
quarkus-qe/quarkus-test-framework pull request #32
Opened 2021-05-14 10:29 UTC by mjurc

* Adding Quarkus source S2I strategy. This strategy utilises OpenShift
  objects generated by the following oc commands:

   ```
   oc import-image --confirm ubi8/openjdk-11 --from=registry.access.redhat.com/ubi8/openjdk-11
   oc new-app ubi8/openjdk-11 <git_path> --context-dir=<context_dir> --name=<project_name>
   ```

  There are additional enhancements, like adding environment variables,
  which are not available from `oc new-app` command.

2021-05-14 12:08 UTC, Sgitario requested changes
Thanks for the PR.
Mainly requested changes:
- Rename fields
- Use service folder instead of temporal folder
- Map quarkus version, package type and others.

2021-05-14 12:12 UTC, mjurc commented on quarkus-test-core/src/main/java/io/quarkus/test/services/QuarkusApplication.java
> +    String[] sourceS2iEnvVars() default {};
One example:

https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/main/external-applications/quarkus-workshop-super-heroes/src/test/resources/hero.yaml#L46

So, for example, if the deployment expects a JDBC connection

2021-05-14 12:13 UTC, mjurc commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/QuarkusSourceS2iBuildApplicationManagedResource.java
> +        if (model.getSourceS2iEnvVars().length > 0) {
Once again, the only motivation was https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/main/external-applications/quarkus-workshop-super-heroes/src/test/resources/hero.yaml#L46

2021-05-14 12:35 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/QuarkusSourceS2iBuildApplicationManagedResource.java
> +        if (model.getSourceS2iEnvVars().length > 0) {
For this, we are using the service properties `.withProperty(x, y)`. You don't need to do anything in s2i related to this, the framework will populate it in the DeploymentConfig automatically.

2021-05-20 21:25 UTC, mjurc commented on quarkus-test-core/src/main/java/io/quarkus/test/utils/ClassPathUtils.java
> +            }
If the developer has no classes in sources (which can happen if they intend to implement a module with only test cases for an application deployed by source S2I build), the methods below this throw NPE and fail the setup.

2021-05-21 04:55 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/utils/ClassPathUtils.java
> +            }
ok ok

2021-05-23 20:50 UTC, mjurc commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/QuarkusSourceS2iBuildApplicationManagedResource.java
> +            result = client.addGitRefToBuildConfig(model.getContext().getOwner().getName(), model.getSourceS2iGitRef(), result);
It's optional, so I thought it would be ok to include the prop only if it's set

2021-05-23 20:50 UTC, mjurc commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/QuarkusSourceS2iBuildApplicationManagedResource.java
> +            result = client.addContextDirToBuildConfig(model.getContext().getOwner().getName(), model.getSourceS2iContextDir(),
It's optional, so I thought it would be ok to include the prop only if it's set

2021-05-23 20:53 UTC, closed without merging