Fix docker rates limits in Jaeger and Mysql
quarkus-qe/quarkus-test-framework pull request #341
Opened 2021-11-23 11:37 UTC by pjgg

We are reaching some limits in Jenkins jobs

Use Quay images instead of DockerHub images:
 
`mysql/mysql-server:8.0` -> `quay.io/quarkusqeteam/mysql-server:8.0`
`jaegertracing/all-in-one:1.21.0` -> `quay.io/jaegertracing/all-in-one:1.21.0`

2021-11-23 12:40 UTC, rsvoboda requested changes
let's not maintain many images on our ow, there is https://quay.io/repository/bitnami/mysql

2021-11-23 15:51 UTC, pjgg commented
> let's not maintain many images on our own, there is https://quay.io/repository/bitnami/mysql
> 
> Also remove `quarkusqeteam/mysql-server` from quay.io

`quarkusqeteam/mysql-server` has been removed from QuarkusQE docker registry and now we are using `https://quay.io/repository/bitnami/mysql`

2021-11-23 16:29 UTC, pjgg commented
run tests

2021-11-24 08:23 UTC, pjgg commented
Errors are located in PingPong module (not related to this PR)

2021-11-24 08:29 UTC, rsvoboda approved these changes

2021-11-24 09:56 UTC, merged