delete project after all property should not scale down services
quarkus-qe/quarkus-test-framework pull request #344
Opened 2021-11-24 16:45 UTC by pjgg

`ts.kubernetes.delete.project.after.all=false` should not scale down k8s/ocp services
Also must only works if `ts.kubernetes.ephemeral.namespaces.enabled=false`

2021-11-24 21:02 UTC, pjgg commented
Pinpong serverless scenario `OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT` is failling by an error not related to this PR 

```
SEVERE Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@14823f76: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

2021-11-25 05:00 UTC, Sgitario requested changes
If you add this code in the stop methods, then when calling the stop method in a test scenario, it wont work. The user would expect the app is stopped but it wont because the ephemeral was enabled...

Therefore, this is not a suitable fix.

Moreover, in k8s there are now two properties: "ts.kubernetes.delete.project.after.all" (this was created here and "ts.kubernetes.delete.namespace.after.all" (the good one as k8s does not know what a project is - this concept is from ocp)

2021-11-25 09:58 UTC, Sgitario requested changes

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +    private static final PropertyLookup DELETE_PROJECT_AFTER = new PropertyLookup("ts.kubernetes.delete.project.after.all",
This property does not make sense in k8s, we should use `DELETE_NAMESPACE_AFTER` instead.

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +        if (isValidConfig && !DELETE_PROJECT_AFTER.getAsBoolean() && ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) {
This logic is wrong, if the KubernetesScenario annotation is not present, we should not check those properties.

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +        context.setDebug(!DELETE_PROJECT_AFTER.getAsBoolean() && !ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean());
nitpick comment: I would add a comment explaining your purpose here: explain better why it should be set DEBUG if these two properties are set.

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +    private static final PropertyLookup ENABLED_EPHEMERAL_NAMESPACES = new PropertyLookup(
This property definition is duplicated in KubectlClient

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java
> +    private static final PropertyLookup ENABLED_EPHEMERAL_NAMESPACES = new PropertyLookup(
This property definition is duplicated in OpenShiftClient.

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java
> +        if (isValidConfig && !DELETE_PROJECT_AFTER.getAsBoolean() && ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) {
This logic is wrong, if the OpenShiftScenario annotation is not present, we should not check those properties.

2021-11-25 09:58 UTC, Sgitario commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java
> +        context.setDebug(!DELETE_PROJECT_AFTER.getAsBoolean() && !ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean());
nitpick comment: I would add a comment explaining your purpose here: explain better why it should be set DEBUG if these two properties are set.

2021-11-25 10:32 UTC, Sgitario commented on quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java
> +        if (isValidConfig && !DELETE_PROJECT_AFTER.getAsBoolean() && ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) {
I read this wrongly. Deleted.

2021-11-25 11:57 UTC, Sgitario approved these changes

2021-11-25 17:50 UTC, merged