Support upstream and product release drafter
quarkus-qe/quarkus-test-framework pull request #406
Opened 2022-02-10 16:57 UTC by pjgg

Publish on GH release [page](https://github.com/quarkus-qe/quarkus-test-framework/releases) an upstream / product release note draft, based on pre-released changes.

Note: at the moment I could not publish Ustream(1.1.x) and product(1.0.x) changes at the same time. Only show up the latest "branch" changes. So, if the latest commit is on main branch then GH release page will publish a 1.1.x release-note draft, called `Next 1.1.x`. 

Related to: #407

Main Doc: https://github.com/release-drafter/release-drafter

2022-02-11 09:38 UTC, mjurc requested changes

2022-02-11 09:38 UTC, mjurc commented on .github/product-release-drafter.yml
> +  ## Product Changes
I don't like the name 'product changes' - we're not releasing any product.

Let's keep it simple and call it `1.0.z`, it's much more obvious

2022-02-11 09:38 UTC, mjurc commented on .github/product-release-drafter.yml
> +name-template: 'Next 1.0.x 🌈'
Let's keep it in line with the name of branch and have it `1.0.z` instead. Change the name of the file as well.

Also, I don't see any branch specifier for this action - keep in mind that for 1.0.z releases, only changed merged to 1.0.z branch should make it to release notes.

2022-02-11 09:38 UTC, mjurc commented on .github/upstream-release-drafter.yml
> +  ## Upstream Changes
Again, let's keep it consistent for branches. I'm fine with just Changes here - after all, this is the upstream for this project.

Let's change the name of this file to something more fitting too.

2022-02-11 09:38 UTC, mjurc commented on .github/upstream-release-drafter.yml
> +name-template: 'Next 1.1.x 🌈'
And once again, I do not see any branch specifier for this action. How does this action know only to include changes merged to `main` for this workflow?

2022-02-11 13:00 UTC, mjurc requested changes

2022-02-11 14:13 UTC, pjgg commented on .github/release-drafter.yml
> +name-template: '1.0.z 🌈'
PR #407 talks about the files that are needed in order to do a release-note draft on branch `1.0.z`
Also as I said in #470 `release-note drafter must be in the main branch, based on some GitHub issues` so `release-drafter.yml` must be in the main branch. 

Doc: https://github.com/release-drafter/release-drafter/issues/398#issuecomment-617928416

2022-02-11 14:15 UTC, mjurc commented on .github/release-drafter.yml
> +name-template: '1.0.z 🌈'
Why do we add a new file, then? I don't get it. We should use the file we must have.

2022-02-11 14:16 UTC, mjurc requested changes
Requesting changes as the review has not been resolved

2022-02-11 14:58 UTC, mjurc commented
After discussion with @pjgg , the issue is that the release note drafter action can only generate a single draft with the latest changes, and that for this draft it is unable to pick a branch for the release to be drafted.

Should we put this on hold until more exploration is done?

2022-02-12 12:03 UTC, pjgg commented
> n hold until more exploration is done?

Yes, let's do another iteration!

2022-02-21 08:38 UTC, mjurc approved these changes
Approving the changes now that I understand the release drafter.

2022-02-21 08:38 UTC, merged