Support platform group ID parametrization
quarkus-qe/quarkus-test-framework pull request #417
Opened 2022-02-23 16:28 UTC by pjgg

Currently the annotation `@GitRepositoryQuarkusApplication` supports the following injections in the mavenArgs annotation property:

* -Dquarkus.platform.version=${QUARKUS_VERSION} 
* -Dquarkus-plugin.version=${QUARKUS-PLUGIN_VERSION} 

Note: if `quarkus-plugin.version` and/or `quarkus.platform.version` is not provided then a default version is set

This PR add a new mavenArg injection:
* -Dquarkus.platform.group-id=${QUARKUS_PLATFORM_GROUP-ID}

If `quarkus.platform.group-id` is not provided then `io.quarkus` would be used as a default group

Usage example:

```
@DisabledOnNative(reason = "This scenario is using uber-jar, so it's incompatible with Native")
@QuarkusScenario
public class TodoDemoIT {
    @GitRepositoryQuarkusApplication(repo = "https://github.com/quarkusio/todo-demo-app.git", mavenArgs = "-Dquarkus.package.type=uber-jar -DskipTests=true -Dquarkus.platform.group-id=${QUARKUS_PLATFORM_GROUP-ID} -Dquarkus.platform.version=${QUARKUS_VERSION} -Dquarkus-plugin.version=${QUARKUS-PLUGIN_VERSION}")
    static final RestService app = new RestService();

    @Test
    public void verify() {
        app.given()
                .get()
                .then()
                .statusCode(HttpStatus.SC_OK);
    }
}
```

Prompt

```
mvn -U clean verify -Dall-modules -Dopenshift -pl external-applications -Dmaven.repo.local=~/Downloads/rh-quarkus-2.2.5.CR3-maven-repository/maven-repository -Dquarkus.platform.group-id=com.redhat.quarkus.platform -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=2.2.5.Final-redhat-00007 -Dquarkus-plugin.version=2.2.5.Final-redhat-00007 
```

This example will use the external application `https://github.com/quarkusio/todo-demo-app.git` with the following maven args:
* quarkus.platform.version=${QUARKUS_VERSION} -> taken from promt -> 2.2.5.Final-redhat-00007
* quarkus-plugin.version=${QUARKUS-PLUGIN_VERSION} -> taken from promt -> 2.2.5.Final-redhat-00007
* quarkus.platform.group-id=${QUARKUS_PLATFORM_GROUP-ID} -> taken from promt -> com.redhat.quarkus.platform

2022-02-23 23:34 UTC, mjurc commented
The new test is failing in all PR builds - @pjgg would you kindly review?

2022-02-24 16:15 UTC, pjgg commented
run tests

2022-02-25 14:03 UTC, pjgg commented
run tests

2022-02-28 23:37 UTC, mjurc requested changes
Besides the `development` branch change, this looks good to me.

2022-02-28 23:37 UTC, mjurc commented on examples/external-applications/src/test/java/io/quarkus/qe/QuickstartUsingDefaultsIT.java
> +    @GitRepositoryQuarkusApplication(repo = "https://github.com/quarkusio/quarkus-quickstarts.git", contextDir = "getting-started", branch = "development")
I am not sure I understand purpose behind using `development` branch.

2022-02-28 23:37 UTC, mjurc commented on examples/external-applications/src/test/java/io/quarkus/qe/QuickstartUsingUsingUberJarIT.java
> +    @GitRepositoryQuarkusApplication(repo = "https://github.com/quarkusio/quarkus-quickstarts.git", contextDir = "getting-started", mavenArgs = "-Dquarkus.package.type=uber-jar -DskipTests=true -Dqua
Same here - why `development` branch? It is not stable.

2022-03-01 12:17 UTC, mjurc approved these changes

2022-03-01 12:17 UTC, merged