Support postgres Bitnami and DockerHub environment variables
quarkus-qe/quarkus-test-framework pull request #456
Opened 2022-04-21 11:05 UTC by pjgg

### Summary

Fix https://github.com/quarkus-qe/quarkus-test-framework/issues/455

Please check the relevant options

- [X] Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [X] Example scenarios have been updated/added
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-04-21 12:03 UTC, fedinskiy requested changes
And do not forget about red CI

2022-04-21 12:03 UTC, fedinskiy commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +public class BitnamiPostgresqlDatabaseIT extends AbstractSqlDatabaseIT {
Name is a bit misleading. `RegistryPostgres`, maybe?

2022-04-21 12:03 UTC, fedinskiy commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +    static final int POSTGRESQL_PORT = 5432;
`private` for all members, maybe?

2022-04-21 12:03 UTC, fedinskiy commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/PostgresqlService.java
> +        // Bitnami environment variables
It's not for bitnami(especially since we do not use it anymore). It is mainly for images from redhat registry, wcich we use in our openshift runs

2022-04-21 13:09 UTC, mjurc commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +public class BitnamiPostgresqlDatabaseIT extends AbstractSqlDatabaseIT {
Is there any value for the future to keep the quay.io container image here, actually?

2022-04-21 13:10 UTC, mjurc commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +public class BitnamiPostgresqlDatabaseIT extends AbstractSqlDatabaseIT {
If we're using DockerHub images from now on, is there any value/use case we'll get from using quay.io ones? Is this mentioned in upstream docs or referenced by any dev service?

2022-04-21 13:22 UTC, fedinskiy commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +public class BitnamiPostgresqlDatabaseIT extends AbstractSqlDatabaseIT {
For some tests, we use `registry.access.redhat.com` images, which use the same options as images from bitnami/quarkus-qe. We cannot use these images in some of our CI's but we need to have compatibility with them.

2022-04-21 15:49 UTC, pjgg commented on examples/database-postgresql/src/test/java/io/quarkus/qe/database/postgresql/BitnamiPostgresqlDatabaseIT.java
> +public class BitnamiPostgresqlDatabaseIT extends AbstractSqlDatabaseIT {
This scenario was removed, following a Michal suggestion. From now, we are not going to support "Bitnami Quay registry".

2022-04-21 16:10 UTC, pjgg commented
BitnamiPostgresqlDatabaseIT scenario has been replaced by `OpenShiftPostgresqlIT` that is pointing to `quay.io/quarkusqeteam/postgres:14.0` that uses an old bitnami postgresql image

2022-04-22 06:57 UTC, fedinskiy requested changes

2022-04-22 06:57 UTC, fedinskiy commented on examples/database-mysql/src/test/java/io/quarkus/qe/database/mysql/DevModeMySqlDatabaseIT.java
> +    @Container(image = "mysql:8.0.27", port = MYSQL_PORT, expectedLog = "Ready for start up")
Can we use `8.0` instead of patch version?

2022-04-22 10:43 UTC, fedinskiy approved these changes
But the CI is red

2022-04-25 19:44 UTC, rsvoboda commented
@pjgg please rebase to pick changes related to CLI / failure with 999-SNAPSHOT

Also, update the title ++ description of the PR, there are more changes attached to this PR

2022-04-26 15:37 UTC, mjurc approved these changes

2022-04-26 15:37 UTC, merged