Add Helm client extension
quarkus-qe/quarkus-test-framework pull request #510
Opened 2022-07-05 17:07 UTC by pjgg

### Summary

This PR introduces Helm client integration into Quarkus Test Framework

Implemented features: 
- Run any Helm command in raw mode: for example `helmClient.run("version")` -> same as `helm version`
- Create an empty Helm chart -> `helmClient.createEmptyChart("chartName")`
- Install a Helm chart -> `helmClient.installChart(...`
- List charts -> `helmClient.getCharts()`
- UninstallCharts -> `helmClient.uninstallChart(chartName)`

More features will be integrated in the future into incoming PRs

Please check the relevant options

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

### Checklist:
- [X] Example scenarios has been updated / added
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-07-15 07:36 UTC, pjgg commented
This PR needs more clarifications from product side

2022-08-06 17:15 UTC, pjgg commented
OCP Failures: `java.lang.RuntimeException: java.io.IOException: Cannot run program "helm" (in directory "target"): error=2, No such file or directory`

2022-08-08 09:06 UTC, pjgg commented
@mjurc ready to be reviewed!

2022-08-11 12:19 UTC, mjurc commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.openshift.expose=true
Do we need this one?

2022-08-11 12:24 UTC, mjurc requested changes

2022-08-11 12:24 UTC, mjurc commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.kubernetes.expose=true
Do we need this one?

2022-08-11 12:24 UTC, mjurc commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.kubernetes.host=examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
Is there any way to parameterize this a little smarter? This will kinda need to be updated for whenever anybody uses a different cluster.

2022-08-11 12:24 UTC, mjurc commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.container-image.tag=v1
Weirdly enough, I am currently getting the same error mentioned in https://github.com/quarkiverse/quarkus-helm/issues/41 even with `quarkus.container-image.tag` specified: 

```
14:21:44,809 INFO  ## Running test OpenShiftQuarkusHelmClientIT.shouldInstallQuarkusAppThroughHelm()
14:21:44,811 INFO  helm install examples-quarkus-helm /home/mjurc/Documents/quarkus-test-framework/examples/quarkus-helm/target/helm/examples-quarkus-helm
14:21:45,877 INFO  Error: INSTALLATION FAILED: validation: chart.metadata.version "1.2.1.Beta3-SNAPSHOT" is invalid
```

2022-08-11 14:22 UTC, pjgg commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.openshift.expose=true
We can remove it is deprecated: https://github.com/quarkiverse/quarkus-helm/issues/47

2022-08-11 14:22 UTC, pjgg commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.kubernetes.expose=true
In the current version, all deprecated params are removed.

2022-08-11 14:27 UTC, pjgg commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.kubernetes.host=examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
Based on the Doc, we could overwrite this property through an environment variable: `QUARKUS_KUBERNETES_HOST`
So, could be customized per job, but if the domain is updated then we have to update this environment too. One solution could be to force this domain to something more semantic:

4-10: latest
4-6: stable

etc...

2022-08-11 14:27 UTC, pjgg commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.container-image.tag=v1
I have updated Quarkus-helm extension to the latest one and the issue was fixed.

2022-08-11 15:41 UTC, pjgg commented on examples/quarkus-helm/src/main/resources/application.properties
> +quarkus.kubernetes.host=examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
Well also is possible to retrieve your application URL from your test by injecting an OpenShiftClient / k8s client

```
@Inject
    static OpenShiftClient ocpClient;
```


And then on your test just call to `url` method:

```
String chartName = "examples-quarkus-helm";
String serviceDomain = ocpClient.url(chartName);
```

2022-08-17 15:51 UTC, pjgg commented
We need to wait for this PR to get merged and released: https://github.com/quarkiverse/quarkus-helm/pull/50

2022-08-18 07:18 UTC, pjgg commented
run tests

2022-08-29 10:42 UTC, pjgg commented
run tests

2022-09-06 14:29 UTC, mjurc commented on examples/quarkus-helm/src/test/java/io/quarkus/qe/helm/QuarkusK8sHelmClientIT.java
> +public class QuarkusK8sHelmClientIT {
Let's go with full platform name naming scheme we got in other examples and call this `QuarkusKubernetesHelmClientIT`.

2022-09-06 14:29 UTC, mjurc commented on examples/quarkus-helm/src/test/java/io/quarkus/qe/helm/QuarkusOcpHelmClientIT.java
> +public class QuarkusOcpHelmClientIT {
Let's go with full platform name naming scheme we got in other examples and call this `QuarkusOpenShiftHelmClientIT`.

2022-09-08 13:22 UTC, merged