Decouple Jaeger from Test core by using OpenTelemetry
quarkus-qe/quarkus-test-framework pull request #516
Opened 2022-07-15 13:04 UTC by michalvavrik

### Summary

`io.jaegertracing:jaeger-client` brings transitively forbidden dependencies we want to avoid. This PR replaces Jaeger client with an OpenTelemetry one as OpenTelemetry is suppported option.

Breaking changes: tracing newly uses `OpenTelemetry Protocol (OTLP) over gRPC` on port `4317` (protocol `HTTP`), and `jaegertracing/all-in-one` in version 1.35+ is required. `ts.global.tracing.jaeger.endpoint` should consist only of a base url (drop `/api/traces`). We need follow-up PR for Jenkins jobs and [upgrade](https://www.jaegertracing.io/docs/1.36/apis/#opentelemetry-protocol-stable) production Jaeger (as its version is 1.30).

I tried to keep as close as possible to the pre-PR state by following this [OpenTelemetry to Jaeger Transformation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md).

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-07-18 09:59 UTC, pjgg requested changes

2022-07-18 09:59 UTC, pjgg commented on extensions/tracing/src/test/resources/test.properties
> +ts.global.tracing.jaeger.endpoint=http://localhost:4317/api/traces
`/api/traces` is still valid?

2022-07-18 09:59 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/QuarkusScenarioAttributes.java
> +    public static final String ERROR = "error";
You ar not using this property at all

2022-07-18 09:59 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TracingExtensionBootstrap.java
> +            quarkusScenarioTracer = new QuarkusScenarioTracer(jaegerHttpEndpoint);
If something goes wrong we want to log the error but continue with the test execution, because scenario tracing is not an stopper. Did you test a `jaegertracing/all-in-one:1.36` fatal error and see if the scenarios continue the regular execution?

2022-07-18 10:07 UTC, pjgg requested changes

2022-07-18 10:07 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/QuarkusScenarioSpan.java
> +    public Span save(Set<String> attributes, ScenarioContext scenarioContext, Throwable throwable) {
Maybe `attributes` could be a Map<String,boolean>` (or you could overwrite this method). This signature will allow us to set the Success attribute to false, onError event.

2022-07-18 10:08 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/QuarkusScenarioTracer.java
> +        quarkusScenarioSpan.save(Set.of(), context, cause).end();
Maybe onError, we could set a success attribute to false
`success=false`

2022-07-18 13:00 UTC, michalvavrik commented on extensions/tracing/src/test/resources/test.properties
> +ts.global.tracing.jaeger.endpoint=http://localhost:4317/api/traces
hmm, looks like path is irrelevant here as `okhttp3.HttpUrl.Builder#parse` only takes a `host` and `port`, however according to the manual [only host and port](https://opentelemetry.io/docs/instrumentation/java/manual/#exporter) should be set, so I'll fix it. Good catch, thanks.

2022-07-18 13:12 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TracingExtensionBootstrap.java
> +            quarkusScenarioTracer = new QuarkusScenarioTracer(jaegerHttpEndpoint);
I took me quite a while to correctly set up Jaeger and when endpoint is both unavailable (f.e. not running)/returns unimplemented (f.e. wrong port), similar message is logged `SEVERE Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317` and testing continues unaffected. I can't pledge for all possible runtime exceptions, but there are no checked and examples on OpenTelemetry reference do no catching (though failure might be blocker for them...). I could only catch `Exception` there, but I don't think it's a good practice.

2022-07-18 13:21 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/QuarkusScenarioAttributes.java
> +    public static final String ERROR = "error";
Jaeger adapter is doing this for us, please have a look https://github.com/open-telemetry/opentelemetry-java/blob/d42c2629b6fb3d4ce1e511454c8e853403cecec7/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java#L116

2022-07-18 13:21 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/QuarkusScenarioAttributes.java
> +    public static final String ERROR = "error";
So I'll drop it.

2022-07-18 14:23 UTC, michalvavrik commented
Thank you for the review.

2022-07-19 09:43 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TracingExtensionBootstrap.java
> +            quarkusScenarioTracer = new QuarkusScenarioTracer(jaegerHttpEndpoint);
This is enough `EVERE Failed to export spans.` thanks!

2022-07-19 09:44 UTC, pjgg approved these changes
LGTM

2022-07-19 09:44 UTC, merged