Using a special class for passing service URIs
quarkus-qe/quarkus-test-framework pull request #535
Opened 2022-08-16 10:10 UTC by fedinskiy

### Summary

### The problem:
All classes, which we use for deploying services in our TS have two methods:
	getHost(returns something like "http://localhost")
	getPort(returns port as integer)
In most places, we call both these methods and then manually glue their output together, sometimes replacing http with other scheme.
In some cases, we have to parse output of getHost() string, since we need only real host name, without a scheme

### The solution:
Replace getHost and getPort with single method getURI, which will return an object of special class, with scheme(e.g. "http"), host(e.g. "localhost") and port(e.g. 8080) at the same time.
We will be able to pick parts of it manually, and glue them with single method.

Initially, I planned to use java.net.URI, but it turns out, that kafka use schemes, which are incompatible with URI standard from IETF and, therefore with java implementation

Closes https://github.com/quarkus-qe/quarkus-test-framework/issues/263

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-08-17 14:17 UTC, pjgg requested changes
Let's try to keep `getHost` and `getPort` method as `@deprecated` and be backward compatible for a couple of releases.

2022-08-31 15:15 UTC, fedinskiy commented
run tests

2022-09-01 08:08 UTC, fedinskiy commented
Fails in Openshift Native are due to OOM/Out of Space during the build, and they do not reproduce themselves in a local run. This PR is ready for a check

2022-09-01 15:35 UTC, pjgg requested changes
Overall looks good but we need also to run OCP coverage

2022-09-01 15:35 UTC, pjgg commented on examples/jaeger/src/test/java/io/quarkus/qe/ClientResourceIT.java
> +            Response response = get(jaeger.getTraceUrl() + "?service=" + SERVICE_NAME);
...and what about this approach?
```
 String traceURL = jaeger.getTraceUrl() + "?service=" + SERVICE_NAME;
            get(traceURL)...
```

2022-09-01 15:35 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public String getRestAssuredStyleUri() {
What do you think about this other method name?

`getRestAssuredStyleUri` -> `toRestAssuredUri`

2022-09-01 15:35 UTC, pjgg commented on quarkus-test-core/src/test/java/io/quarkus/test/services/URILikeTest.java
> +import static org.junit.jupiter.api.Assertions.*;
is not used !

2022-09-01 15:35 UTC, pjgg commented on quarkus-test-core/src/test/java/io/quarkus/test/services/URILikeTest.java
> +    void string() {
Better test name, something like `stringSerialization` ...

2022-09-01 15:35 UTC, pjgg commented on quarkus-test-core/src/test/java/io/quarkus/test/services/URILikeTest.java
> +    void string() {
Could we verify some border conditions, for example, If I create a `URILike` without scheme...make sense? and IF does which should be the expected result? 

`URILike uri = new URILike("", "localhost", 1102, null);` -> `://localhost:1102` ?

or the port has some limits, could we have a negative port? ... think in border conditions and be sure that we have the expected response for these cases.

2022-09-01 15:35 UTC, pjgg commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftQuarkusApplicationManagedResource.java
> +        if (protocol == Protocol.HTTPS && !client.isServerlessService(model.getContext().getName())) {
I think that this validation could be in a private method as it was in main branch, WDYT?

2022-09-02 06:42 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public String getRestAssuredStyleUri() {
"Rest Assured URI" looks like it is URI, which points to Rest Assured while this method returns URI, which can be accepted by RestAssured. Probably we can use getUriForRestAssured, but in one or two places it used for other things, so the name would be a bit misleading

2022-09-02 10:04 UTC, fedinskiy commented on examples/jaeger/src/test/java/io/quarkus/qe/ClientResourceIT.java
> +            Response response = get(jaeger.getTraceUrl() + "?service=" + SERVICE_NAME);
Removed this stuff altogether

2022-09-02 10:04 UTC, fedinskiy commented on quarkus-test-core/src/test/java/io/quarkus/test/services/URILikeTest.java
> +    void string() {
Renamed and added some tests. Thank you to pointing me to this

2022-09-02 10:44 UTC, fedinskiy commented
run tests

2022-09-02 11:31 UTC, pjgg commented on quarkus-test-core/src/test/java/io/quarkus/test/services/URILikeTest.java
> +class URILikeTest {
Too much better!

2022-09-02 11:32 UTC, pjgg approved these changes
LGTM

2022-09-02 15:05 UTC, merged