Updated jvm and native Dockerfiles
quarkus-qe/quarkus-test-framework pull request #537
Opened 2022-08-18 13:18 UTC by jirisimek98

Updated Dockerfiles since the outdated ones have issues running on OCP 4.11

2022-08-18 16:21 UTC, pjgg requested changes
Thank you @jirisimek98 for your PR, just a few comments

2022-08-18 16:21 UTC, pjgg commented on quarkus-test-images/src/main/resources/Dockerfile.jvm
> +COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
These docker files are not the final ones, are like "templates" and pre-processing by functions like this one: https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-images/src/main/java/io/quarkus/test/utils/DockerUtils.java#L52

So could you replace the word `target` by `${ARTIFACT_PARENT}`

Line: 85, 86 and 87

2022-08-18 16:21 UTC, pjgg commented on quarkus-test-images/src/main/resources/Dockerfile.native
> +COPY --chown=1001:root target/*-runner /work/application
Same "target" replacement is needed.

2022-08-23 09:03 UTC, fedinskiy approved these changes
Looks good to me, but let's wait for CI

And could you bring back that newline at the end of Dockerfile.native? :-)

2022-08-23 12:56 UTC, fedinskiy commented
run tests

2022-08-24 07:06 UTC, fedinskiy commented
run tests

2022-08-24 11:10 UTC, mjurc approved these changes
CI failures are unrelated.

LGTM, thanks for the update!

2022-08-24 11:10 UTC, merged