Ability to add test tracing
quarkus-qe/quarkus-test-framework pull request #55
Opened 2021-05-25 14:45 UTC by pjgg

The test framework will trace all your test/method invocations, so you can review how much time took to run a test
or filter by tags or errors.

2021-05-26 05:51 UTC, Sgitario requested changes
Summary:
- I think the tracer should be an optional feature (it should implement `ExtensionBootstrap`).
The `QuarkusScenarioBootstrap` should do only a single thing: bootstrap the test components (services, extensions, annotations).
- Properties should start with "ts."
- Missing coverage of this feature (I think we could add some test development to ensure the correct integration with Jaeger).

2021-05-26 05:51 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/QuarkusScenarioBootstrap.java
> +            testFrameworkTracer.finishWithSuccess(context, Sets.newHashSet(service.getName()));
I don't see the value of adding the service name as a tag :/

2021-05-26 05:51 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TestFrameworkTracer.java
> +public class TestFrameworkTracer {
I would rename the class to QuarkusScenarioTracer.

2021-05-26 05:51 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TestFrameworkTags.java
> +public class TestFrameworkTags {
Why this logic can't go in the tracer?

2021-05-26 05:51 UTC, Sgitario commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TestFrameworkTracer.java
> +    private static final String DEFAULT_JAEGER_HTTP_ENDPOINT = "http://localhost:14268/api/traces";
Use `PropertyLookup` for this purpose that allows you to set a defaults.
Also, all the properties for the test framework should start with "ts."

2021-05-26 16:15 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/QuarkusScenarioBootstrap.java
> +            testFrameworkTracer.finishWithSuccess(context, Sets.newHashSet(service.getName()));
In the end is easier to filter by Jaeger

2021-05-26 16:16 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/tracing/TestFrameworkTags.java
> +public class TestFrameworkTags {
Because of Tracer, Tags, Span... start growing in terms of methods and I think that is easier to maintain with segregated responsibilities.

2021-05-26 16:29 UTC, pjgg commented
Missing coverage of this feature

2021-05-31 12:32 UTC, Sgitario commented on examples/TracingExtension/pom.xml
> +    <artifactId>examples-tracingExtension</artifactId>
In order to follow the rest of the examples name convention, it should be: `examples-tracing-extension` or maybe simply `examples-tracing`.

2021-05-31 12:32 UTC, Sgitario commented on examples/TracingExtension/pom.xml
> +    <name>Quarkus - Test Framework - Examples - tracingExtension</name>
Same here: Quarkus - Test Framework - Example - Tracing

2021-05-31 12:32 UTC, Sgitario commented on pom.xml
> +                <module>examples/TracingExtension</module>
same: tracing or tracing-extension

2021-05-31 12:32 UTC, Sgitario commented on quarkus-test-core/pom.xml
> +            <artifactId>quarkus-smallrye-opentracing</artifactId>
Do we need this dependency? This is bound to Quarkus releases and as far I see, we only need it for `io.jaegertracing` and `o.opentracing`, so we could add the jaeger dependencies directly. This way we keep the dependencies with Quarkus as lower as possible.

2021-06-01 05:03 UTC, Sgitario approved these changes

2021-06-01 05:03 UTC, merged