Bump Jaeger all-in-one from 1.30.0 to 1.37.0
quarkus-qe/quarkus-test-framework pull request #552
Opened 2022-09-05 14:52 UTC by michalvavrik

### Summary

Bumps Jaeger _all-in-one_ from 1.30.0 to 1.37.0 as we want to use OTLP exporter instead of Jaeger exporter and this feature was [only introduced in 1.36.0](https://www.jaegertracing.io/docs/1.36/apis/#opentelemetry-protocol-stable).

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] (kinda) Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-09-05 22:29 UTC, michalvavrik commented
run tests

2022-09-06 07:02 UTC, michalvavrik commented
OpenShift failure - _Examples - Ping Pong_ is not related to this PR.

2022-09-06 07:51 UTC, pjgg requested changes
I will try to be backward compatible and leave the current example pointing to the Rest HTTP  API, by adding a new OLTP example.

2022-09-06 07:51 UTC, pjgg commented on examples/jaeger/src/main/resources/application.properties
> +quarkus.opentelemetry.enabled=true
by default is true, I will remove it to check if default value changes in the future

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java
> +    int restPort() default 4317;
This port is OTLP gRPC receiver (Grpc is Http2 -> https + protobuf as body(binary body))

I will keep 14268 as RestPort as, it is and then add a new oltpPort

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java
> +    int restPort() default 4317;
And also could you add some comments in order to explain what each port means?

default 14268 # Http receiver
default 4317 # OTLP gRPC receiver

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerGenericDockerContainerManagedResource.java
> +        }
```
private String getJaegerTraceUrl() {
        return getURI(Protocol.HTTP)
                .withPort(getMappedPort(model.getTracePort()))
                .toString();
    }
```

I think that this method should reflect... if OLTP exporter is enabled or not in order to use one port or the other (and HTTP or HTTPS)

2022-09-06 07:51 UTC, pjgg commented on examples/jaeger/src/test/java/io/quarkus/qe/ClientResourceIT.java
> +            .withProperty("quarkus.opentelemetry.tracer.exporter.otlp.endpoint", jaeger::getRestUrl);
`jaeger::getRestUrl` ... maybe should be `jaeger::getOltpUrl` ?

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/OpenShiftJaegerContainerManagedResource.java
>  }
Also in `JaegerService` there are some references to some system property `ts.jaeger.trace.url` or some HTTP rest references `public String getRestUrl() {
        return getURI(Protocol.HTTP).withPath(JAEGER_API_PATH).toString();
    }`

Maybe some changes are need it in order to reflect OLTP support.

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/resources/jaeger-deployment-template.yml
>                    protocol: UDP
I think that in the `service.yaml` we are missing the OLTP port isn't?

```
 spec:
      ports:
        - name: query-http
          port: ${TRACE_PORT}
          protocol: TCP
          targetPort: ${TRACE_PORT}
```

2022-09-06 07:51 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/resources/jaeger-deployment-template.yml
>                    protocol: UDP
Maybe the best approach is just add a new service as this one but instead of Rest point to OLTP (but keep rest service too)
```
 - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-rest'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-rest'
          port: ${INTERNAL_PORT}
          protocol: TCP
          targetPort: ${INTERNAL_PORT}
      selector:
        app: '${SERVICE_NAME}'

```

2022-09-06 08:27 UTC, michalvavrik commented on examples/jaeger/src/main/resources/application.properties
> +quarkus.opentelemetry.enabled=true
I just followed guide where this flag is also explicitly set to true https://quarkus.io/guides/opentelemetry. I'll drop it, thanks

2022-09-06 09:29 UTC, michalvavrik commented on quarkus-test-service-jaeger/src/main/resources/jaeger-deployment-template.yml
>                    protocol: UDP
We are not missing the OTLP port here as affected port is not `TRACE_PORT`, but `INTERNAL_PORT`. 
IMHO `INTERNAL_PORT` is good enough to be used with both OTLP and REST. I don't have one service (either rest or otlp) that is not used (it's also verbose), thus I renamed it to `-collector`. Is that okay?

2022-09-06 09:36 UTC, michalvavrik commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/OpenShiftJaegerContainerManagedResource.java
>  }
Trace URL is not related to the changes. Just because we give an option to use an OTLP exporter, it does not mean you have to query traces in a different fashion.

2022-09-06 09:38 UTC, michalvavrik commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerGenericDockerContainerManagedResource.java
> +        }
I don't agree - this is trace URL - AKA the URL to query traces. We newly allow you to collect traces via OTLP (gRPC) instead of jaeger.thrift, but AFAIK there are no requirements to change the way you query traces. I'd prefer to add HTTPS only when someone really needs it (not the case ATM).

2022-09-06 09:39 UTC, michalvavrik commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java
> +    int restPort() default 4317;
Done, thank you for suggestions.

2022-09-06 09:40 UTC, michalvavrik commented on examples/jaeger/src/test/java/io/quarkus/qe/ClientResourceIT.java
> +            .withProperty("quarkus.opentelemetry.tracer.exporter.otlp.endpoint", jaeger::getRestUrl);
use was more generic as the return value is composed in the same fashion for both rest and otlp URL. It would be weird to have 2 methods doing a same.

2022-09-06 09:49 UTC, michalvavrik commented
@pjgg thank you for suggestion. I incorporated them and also changed a description of the PR as substance changed a little bit.

2022-09-06 09:49 UTC, michalvavrik commented
run tests

2022-09-06 11:03 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java
> +    /**
That is very cool!

2022-09-06 11:06 UTC, pjgg approved these changes

2022-09-06 11:06 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerContainerManagedResourceBuilder.java
> +    private int port;
ok this is a breaking change, could you add a note to the description of the PR

2022-09-06 11:06 UTC, pjgg commented on quarkus-test-service-jaeger/src/main/resources/jaeger-deployment-template.yml
>                    protocol: UDP
Yes, make sense!

2022-09-06 11:08 UTC, pjgg commented
LGTM

2022-09-06 11:18 UTC, michalvavrik commented on quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerContainerManagedResourceBuilder.java
> +    private int port;
I think it's not breaking as by default behavior is same (as `useOtlpCollector` is false), but you are right it should be emphasized in the description. Done.

2022-09-06 12:19 UTC, michalvavrik commented
OC failure - `Examples - Ping Pong` is not related.

2022-09-06 12:56 UTC, michalvavrik commented
OC native has following not related failures
```
[io.quarkus.qe.OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT.io.quarkus.qe.OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT](https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-native-githubci/176/testReport/junit/io.quarkus.qe/OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT/io_quarkus_qe_OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT/)
[io.quarkus.qe.OpenShiftUsingExtensionAndServerlessPingPongResourceIT.io.quarkus.qe.OpenShiftUsingExtensionAndServerlessPingPongResourceIT](https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-native-githubci/176/testReport/junit/io.quarkus.qe/OpenShiftUsingExtensionAndServerlessPingPongResourceIT/io_quarkus_qe_OpenShiftUsingExtensionAndServerlessPingPongResourceIT/)
```

2022-09-06 12:57 UTC, merged