Fix for a failing Kafka operator job
quarkus-qe/quarkus-test-framework pull request #595
Opened 2022-10-12 15:15 UTC by fedinskiy

### Summary

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-10-13 11:54 UTC, pjgg commented
run tests

2022-10-13 12:06 UTC, pjgg requested changes
Minor changes or clarifications

2022-10-13 12:06 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    //todo workaround for https://github.com/fabric8io/kubernetes-client/issues/4491
Could you write "//todo" keyword in upper case as others project "//TODO"s

2022-10-13 12:06 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
Did you see any concurrency issue that justifies the use of an atomic variable?

2022-10-13 12:16 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
Not at the moment, but with asynchronous nature of quarkus and blackbox of junit it is better safe, than sorry

2022-10-13 12:19 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    //todo workaround for https://github.com/fabric8io/kubernetes-client/issues/4491
done

2022-10-13 13:31 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
I prefer don't add code that is not 100% required. Please be sure that we are dealing with concurrency issues before proceeding with this request.

2022-10-13 13:51 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
We definitely need to mark the job as already stopped, so this code is 100% required. I prefer to guarantee, that this protects us from race conditions, than investigate it later.

2022-10-13 13:56 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
On the second thought, in this case it is volatile field and synchronous method, what we should use.

2022-10-13 18:39 UTC, pjgg commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
> We definitely need to mark the job as already stopped, so this code is 100% required
- agree!

>  I prefer to guarantee, that this protects us from race conditions, than investigate it later.
- I am not 100% sure about the "What If" programming to be honest. I see your point, but I would prefer to make this PR without the synchronization and in a different PR try to find a real use case where we can see a race condition and then fix it. Maybe this problem is in another methods too as ...start, close...etc also maybe we should double-check child classes that currently are extending baseService... etc In my opinion the synchronization part is not...part of this PR. 
WDYT ? @fedinskiy

2022-10-14 12:30 UTC, mjurc commented on quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/BaseService.java
> +    private final AtomicBoolean isStopped = new AtomicBoolean(false);
I agree with @pjgg about being careful with changing behavior of base class that 22 classes extend, and about concurrency issues.

The PR proposes to change `BaseService` that is inherited by 22 classes because operator-managed Kafka service is getting `io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Kafka]  with name: [kafka-instance]  in namespace: [ts-qgrutdkgws]  failed` exception. We can read out where the issue from the stacktrace:

```
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getMandatory(BaseOperation.java:177)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:139)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:88)
	at io.quarkus.test.bootstrap.inject.OpenShiftClient.isCustomResourceReady(OpenShiftClient.java:503)
	at io.quarkus.test.services.operator.OperatorManagedResource.lambda$customResourcesAreReady$0(OperatorManagedResource.java:87)
```

This points us [here](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/services/operator/OperatorManagedResource.java#L86). This method is what should be changed for now to be more robust, and with the changes in fabric8 client 6, I presume now we're getting an exception from [here](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java#L503) rather than `null` value in fabric8 client 5, which the previously linked `isCustomResourceReady` method mentioned.

So, we should change the linked failure spots.

The other big issue with this proposal is semantics. We cannot have both `isRunning` and `isStopped` booleans without atomically ensuring they're in consistent state compared to eachother, cos that's gonna lead to some really ugly expectations and some seriously weird state machines for those two states.

2022-10-14 12:32 UTC, mjurc requested changes
I agree with @pjgg about being careful with changing behavior of base class that 22 classes extend, and about concurrency issues.

The PR proposes to change `BaseService` that is inherited by 22 classes because operator-managed Kafka service is getting `io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Kafka]  with name: [kafka-instance]  in namespace: [ts-qgrutdkgws]  failed` exception. We can read out where the issue comes from in the stacktrace:

```
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getMandatory(BaseOperation.java:177)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:139)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:88)
	at io.quarkus.test.bootstrap.inject.OpenShiftClient.isCustomResourceReady(OpenShiftClient.java:503)
	at io.quarkus.test.services.operator.OperatorManagedResource.lambda$customResourcesAreReady$0(OperatorManagedResource.java:87)
```

This points us [here](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/services/operator/OperatorManagedResource.java#L86). This method is what should be changed for now to be more robust, and with the changes in fabric8 client 6, I presume now we're getting an exception from [here](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java#L503) rather than `null` value in fabric8 client 5, which the previously linked `isCustomResourceReady` method mentioned handles.

So, we should change the linked failure spots.

The other big issue with this proposal is semantics. We cannot have both `isRunning` and `isStopped` booleans without atomically ensuring they're in consistent state compared to eachother, cos that's gonna lead to some really ugly expectations and some seriously weird state machines for those two states.

2022-10-14 15:09 UTC, fedinskiy commented
@mjurc issue points us here, but the issue is a symptom, not a cause. There is a linked issue[1] in comments, and according to discussion in this thread, this issue is caused by an attempt to stop the service twice( as part of junit afterall routine and as part of closing routine). I guess you can agree, that closing a service twice is not a normal behaviour for any of 22 different types of service we have. Also, I would like to point out, that this change does not add concurrency issues, but prevents them(even if we do not have them right now).

I agree with the notion about state machines stuff. What do you think about moving isStopped check into isRunning method(and synchronising isRunning method as well)?

[1] https://github.com/fabric8io/kubernetes-client/issues/4491

2022-10-17 09:24 UTC, fedinskiy commented
@mjurc we discussed this in person and decide to let you think about it. Current version was updated to have `isStopped` check inside `isRunning` method

2022-10-23 19:39 UTC, michalvavrik commented
I can't understand why `#isRunning` that doesn't make any write operation should be synchronized. If you are afraid that there is expensive remote call than synchronized won't help there, and you already have `#stop` synchronized. Please elaborate.

2022-10-30 14:05 UTC, closed without merging

2022-10-30 14:05 UTC, mjurc commented
Superseded by #608