Check logs to ensure Kafka container is ready
quarkus-qe/quarkus-test-framework pull request #599
Opened 2022-10-18 19:42 UTC by michalvavrik

### Summary

Updates Strimzi and Confluent Kafka images to the latest versions and adds extra check that inspect container logs to determine whether Kafka is ready. After investigating Test Suite [Daily Build #608](https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/3257533483) and `StrimziKafkaStreamIT` itself, I'm not completely sure that Kafka was ready when tests started.

[If I get it right](https://www.testcontainers.org/features/startup_and_waits/), currently we are using default `IsRunningStartupCheckStrategy` strategy that is just checking if container reached running state with start up timeout. I've added additional `WaitStrategy` that makes sure Kafka is ready. We already are doing same in `OpenShiftStrimziKafkaContainerManagedResource`.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-10-18 21:02 UTC, michalvavrik commented
Failed test on Windows doesn't seem to be related.

2022-10-19 14:06 UTC, pjgg approved these changes
LGTM

2022-10-19 14:08 UTC, pjgg requested changes
Do we need to backport these changes? 

Could you have a look Windows CI errors? 

Where did the selected Kafka version come from? are we using these versions on Quickstart?

2022-10-19 14:45 UTC, pjgg approved these changes
LGTM

2022-10-19 14:46 UTC, merged