Fix git Maven params
quarkus-qe/quarkus-test-framework pull request #649
Opened 2023-01-11 13:25 UTC by llowinge

### Summary

Maven arguments for GitRepository apps should be provided only via https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/java/io/quarkus/test/services/GitRepositoryQuarkusApplication.java#L17 - so i've removed hardcoded `quarkus.version` and `quarkus-plugin.version` from `GitRepositoryResourceBuilderUtils` (i can add them as default to https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/java/io/quarkus/test/services/GitRepositoryQuarkusApplication.java#L17 if you wish).

Also i've modified S2I template because it was using the same ENV variable for both `quarkus.version` and `quarkus.platform.version` which is not true in case of Platform build.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-01-11 13:35 UTC, rsvoboda commented
run tests

2023-01-12 08:27 UTC, llowinge commented
@rsvoboda Do you have solution for the failures ? Obviously jobs are not using `QUARKUS_PLATFORM_VERSION` which i've added. What can i do about it ?

2023-01-12 16:01 UTC, llowinge commented
@pjgg @mjurc FYI

2023-01-23 22:22 UTC, mjurc commented
@llowinge For source S2I on OpenShift, please look at https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftS2iGitRepositoryQuarkusApplicationManagedResource.java#L83.

As for using `quarkus.version`... We should probably get rid of that altogether - there is not a scenario when we should be using `io.quarkus:quarkus-bom` version for source S2I builds in OpenShift. The product itself does not support usage of non-platform boms, and they may not be shipped in the future.

2023-01-23 22:23 UTC, mjurc requested changes
@llowinge For source S2I on OpenShift, please look at https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftS2iGitRepositoryQuarkusApplicationManagedResource.java#L83.

As for using `quarkus.version`... We should probably get rid of that altogether - there is not a scenario when we should be using `io.quarkus:quarkus-bom` version for source S2I builds in OpenShift. The product itself does not support usage of non-platform boms, and they may not be shipped in the future.

2023-01-25 09:51 UTC, llowinge commented
run tests

2023-01-25 11:33 UTC, mjurc commented
run tests

2023-01-26 13:01 UTC, mjurc approved these changes
LGTM, thank you for the fix!

2023-01-26 13:01 UTC, merged