Jakarta migration - fix FW injection by migration remaining imports
quarkus-qe/quarkus-test-framework pull request #674
Opened 2023-02-09 20:46 UTC by michalvavrik

### Summary

https://github.com/quarkus-qe/quarkus-test-framework/pull/668 follow-up where I missed javax Inject

Please check the relevant options

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [X] Example scenarios has been updated / added
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-02-09 20:47 UTC, michalvavrik commented
Blocks https://github.com/quarkus-qe/quarkus-test-suite/pull/1049

2023-02-09 23:07 UTC, michalvavrik commented
run tests

2023-02-09 23:52 UTC, michalvavrik commented
run tests

2023-02-10 07:33 UTC, fedinskiy requested changes
And please check the CI

2023-02-10 07:33 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftS2iGitRepositoryQuarkusApplicationManagedResource.java
> +            "quay.io/quarkus/ubi-quarkus-graalvmce-s2i:22.3-java17");
I remember there were some complication, about proper usage of images. Is it the correct one?

And this change is neither in the PR description nor in the text of the commit.

2023-02-10 09:27 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftS2iGitRepositoryQuarkusApplicationManagedResource.java
> +            "quay.io/quarkus/ubi-quarkus-graalvmce-s2i:22.3-java17");
You are correct, this change is in this commit by mistake (good catch btw!! I was trying to test whether it works). However strictly speaking it is according to what should be there as you can read here https://github.com/quarkusio/quarkus/issues/30829#issuecomment-1422548366. Currently all related tests are (and going to be in TS too) disabled anyway, there is still TODO. Please let me correct comment in separate issue as this one is rather urgent (it blocks me in TS). But I'll respect any preference you have to fix this...

2023-02-10 09:29 UTC, michalvavrik commented
I'll check CI ASAP and get back here.

2023-02-10 09:40 UTC, michalvavrik commented
OC native failure is due to _There is insufficient memory for the Java Runtime Environment to continue._, IMHO not related.

2023-02-10 10:54 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftS2iGitRepositoryQuarkusApplicationManagedResource.java
> +            "quay.io/quarkus/ubi-quarkus-graalvmce-s2i:22.3-java17");
got rid of it

2023-02-10 10:55 UTC, fedinskiy approved these changes

2023-02-10 11:00 UTC, merged