Support deployment of applications with management interface via openshift extension
quarkus-qe/quarkus-test-framework pull request #737
Opened 2023-04-14 14:45 UTC by fedinskiy

### Summary
Applications, which use separate network interface for management can now be deployed by openshift extension
Be aware, that https connection for the interface is not enabled upstream, so it is disabled in tests.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-04-15 08:43 UTC, michalvavrik requested changes
I tested OC failures with and without your PR and they are related, please have a look.

2023-04-15 08:43 UTC, michalvavrik commented on quarkus-test-openshift/src/main/resources/quarkus-build-openshift-template.yml
> +                  port: ${MANAGEMENT_PORT}
Why are readiness and liveness probe always on management port even when management interface is disabled?

2023-04-15 08:43 UTC, michalvavrik commented on quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
> +    name: "${SERVICE_NAME}-management"
I don't understand this part - we create service `${SERVICE_NAME}-management` but we never create pods for it, shouldn't you instead add (conditionally enhance template if management interface is really needed) additional port to the existing `${SERVICE_NAME}`? You can have more than one port  there.

2023-04-15 08:43 UTC, michalvavrik commented on quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
> +              port: ${MANAGEMENT_PORT}
I think this should only be management port when management interface is really enabled.

2023-04-17 07:11 UTC, fedinskiy commented on quarkus-test-openshift/src/main/resources/quarkus-build-openshift-template.yml
> +                  port: ${MANAGEMENT_PORT}
When we do not have management interface active, the "MANAGEMENT_PORT" variable is 8080

2023-04-17 07:16 UTC, fedinskiy commented on quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
> +    name: "${SERVICE_NAME}-management"
We do not need new pod, there can be several services for a single pod, as in this case.
I tried the way with several routes for a same service, but it fails, when pod port is different from route port ( looks like a  bug in Openshift).
Conditional enhancing of template would overcomplicate things, I would like to avoid this as much as possible.

2023-04-17 07:16 UTC, fedinskiy commented on quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
> +              port: ${MANAGEMENT_PORT}
When management interface is disabled, management port is 8080

2023-04-17 07:32 UTC, michalvavrik commented on quarkus-test-openshift/src/main/resources/quarkus-build-openshift-template.yml
> +                  port: ${MANAGEMENT_PORT}
noted, see in the other comment thread for my response

2023-04-17 07:36 UTC, michalvavrik commented on quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
> +    name: "${SERVICE_NAME}-management"
Thanks for explanation, I'll check with docs later today and resolve this comment.

2023-04-17 11:05 UTC, fedinskiy commented
run tests

2023-04-17 13:53 UTC, michalvavrik commented
run tests

2023-04-17 15:31 UTC, fedinskiy commented
run tests

2023-04-18 06:58 UTC, fedinskiy commented
run tests

2023-04-18 09:39 UTC, michalvavrik approved these changes
LGTM

2023-04-18 09:40 UTC, merged