Enable Quarkus Quickstart tests
quarkus-qe/quarkus-test-framework pull request #754
Opened 2023-04-21 15:48 UTC by gtroitsk

### Summary

Enable Quarkus Quickstart tests. 
Make quarkus app from development branch that uses Quarkus 3 so we can test it before Quarkus Quickstarts main starts using Quarkus 3.0.0.Final

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-04-21 16:13 UTC, michalvavrik approved these changes
Thanks!

2023-04-21 16:13 UTC, michalvavrik commented
run tests

2023-04-21 17:17 UTC, michalvavrik requested changes
Yeah, QS development branch works with snapshot and we don't have it in CI available :-) Didn't realize, let's replace original `@Disabled` with `@EnabledOnQuarkusVersion(version = "999-SNAPSHOT", reason = "bla bla")`

2023-04-22 10:01 UTC, gtroitsk commented
run tests

2023-04-22 15:04 UTC, merged