Fix/mysql fips
quarkus-qe/quarkus-test-framework pull request #764
Opened 2023-04-26 14:34 UTC by fedinskiy

### Summary

 Add FIPS-specific query parameters
    
  Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/756

Also, fix for openshift-template typo

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-04-26 14:44 UTC, michalvavrik requested changes

2023-04-26 14:44 UTC, michalvavrik commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/MySqlService.java
> +                .toString();
there is no FIPS in `getJdbcUrl` name, can we only add this options if environment variable `FIPS` is set to `fips`? I don't want to alter connection string unless we really need to

2023-04-26 14:47 UTC, fedinskiy commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/MySqlService.java
> +                .toString();
This behavior should work in ordinary mode too.
And reading environment variables in a method is sort of antipattern, since it is not explicit

2023-04-26 14:52 UTC, michalvavrik commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/MySqlService.java
> +                .withScheme(getJdbcName())
at which point is added `vertx-reactive:` before `mysql`?

2023-04-26 14:54 UTC, michalvavrik commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/MySqlService.java
> +                .withScheme(getJdbcName())
okay,  I can see `io.quarkus.test.bootstrap.DatabaseService#getReactiveUrl` does same, so I suppose it do work

2023-04-26 15:03 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public URILike withQuery(String query) {
please add new method (getter) `getQuery` for cases someone want to join query with the previous one

2023-04-26 15:05 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public URILike withQuery(String query) {
Do we have such cases?

2023-04-26 15:08 UTC, fedinskiy commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public URILike withQuery(String query) {
I would prefer to keep api size as small as possible.
For context, existing `getUserInfo` isn't used anywhere outside unit tests for this class.

2023-04-26 15:09 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/services/URILike.java
> +    public URILike withQuery(String query) {
ok

2023-04-26 15:11 UTC, michalvavrik approved these changes
I dislike always adding FIPS_OPTIONS, but approved, thanks for the fix

2023-04-26 15:26 UTC, michalvavrik commented on quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/MySqlService.java
> +    private static final String FIPS_OPTIONS = "useSSL=false&allowPublicKeyRetrieval=True";
can you add TODO to switch from `useSSL` to `sslMode` when all our MySQL versions are greater or equal to 8.0.13?

2023-04-26 17:15 UTC, rsvoboda commented
Going forward I think we should consider different approach for FIPS enabled environment. We may have other environments with some specifics and we should have a more general way for treating different environments.

I have no concrete solution in mind, maybe something like environment based enrichers. These enricher can be applied in the services, or Enrichers would be just information holders and each service could adapt on their own.
We need to decide if we are running against bare metal or OCP, we could also track target environment specifics. We may need to run against FIPS enabled OCP which could some specifics comparing to fips enabled RHEL.

@mjurc @michalvavrik wdyt?

About this PR: I don't like that the jdbc url is always altered even though fips enable use-case is not the major one. We must just hope it won't introduce side effects in the future.

2023-04-26 17:28 UTC, michalvavrik commented
> I have no concrete solution in mind, maybe something like environment based enrichers. These enricher can be applied in the services, or Enrichers would be just information holders and each service could adapt on their own. We need to decide if we are running against bare metal or OCP, we could also track target environment specifics. We may need to run against FIPS enabled OCP which could some specifics comparing to fips enabled RHEL.

IMO it's only worth effort when we have more FIPS specific customizations because it will come with a cost - boilerplate/extra code for abstraction

as far as this PR is concerned @fedinskiy, approval still holds, but I realized 2 things:

- I'd like to run OpenShift tests because of template change (I didn't write `run tests` as I hope you will address my comment)
- if I read this https://github.com/quarkusio/quarkus/issues/32910#issuecomment-1523711393 correctly, your fix won't help for the moment being as it won't work anyway (not in JVM mode, not in native mode). Am I wrong? Shouldn't we wait and test your changes when upstream issue is fixed so that we have way to verify them (don't get me wrong, I trust you)

2023-04-26 17:30 UTC, michalvavrik commented
ouch, so just mentioning r*u*n tests anywhere in code triggers job :-D

2023-04-28 07:09 UTC, rsvoboda commented
@fedinskiy / @michalvavrik is the fail related to the change / can be the PR merged?

2023-04-28 07:53 UTC, michalvavrik commented
> @rsvoboda the fail is not related, but I think the PR **should not** be merged (see above).

+1 please don't merge; it won't work in native or JVM anyway till upstream provide supported (customer friendly) way, I vote for waiting to upstream issue fix.

2023-04-28 07:57 UTC, rsvoboda commented
> I vote for waiting to upstream issue fix

So we should close this PR for now?

2023-04-28 07:59 UTC, michalvavrik commented
> > I vote for waiting to upstream issue fix
> 
> So we should close this PR for now?

That's what I tried not to say(but thought), maybe @fedinskiy have other plans as we watch upstream issue closely

2023-05-15 13:28 UTC, fedinskiy commented
This PR tries to solve https://github.com/quarkusio/quarkus/issues/32910 in a wrong way, so waiting for proper upstream fix is probably a better idea.

2023-05-15 13:28 UTC, closed without merging