Do not manage HTMLUnit and Jaeger client dependencies
quarkus-qe/quarkus-test-framework pull request #781
Opened 2023-05-12 13:18 UTC by michalvavrik

### Summary

We don't use Jaeger client and HTMLUnit in Test Framework and shouldn't waste dependabot runs on them. If anything that depends on our framework actually needs this dependencies, it should manage them itself.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-05-15 08:53 UTC, michalvavrik commented
I'll rebase to resolve conflicts.

2023-05-16 09:30 UTC, jsmrcka requested changes

2023-05-16 09:30 UTC, jsmrcka commented on pom.xml
> -            </dependency>
This dependency is used in QE TS in several modules, e.g. https://github.com/quarkus-qe/quarkus-test-suite/blob/4ad7c428a48f4dbaaae90cbd88066d9c12e1225a/security/keycloak-jwt/pom.xml#L22.

Unless we manage the dependency there (likely in the TS's root pom), it would not compile.

Also, there is a logging level set in TF: https://github.com/quarkus-qe/quarkus-test-framework/blob/7a6f350295e4633dd10d6650aec8c0181d0c5cd2/quarkus-test-core/src/main/resources/logging.properties#L4.
If the dependency is removed from TF, we should IMO remove this property as well.
But that also means figuring out a way to apply it in the TS. Otherwise, the `htmlunit` logging output would start littering TS logs.

2023-05-16 10:49 UTC, michalvavrik commented on pom.xml
> -            </dependency>
@jsmrcka I can drop logging, although I don't see anything bad on setting it here because this way, it is set for all tests that could be using it (though TBH, I think it's remnant as I got rid of HTML unit from test-core and now it is not used there!). 

But whether or not TS decides to manage something, it's not FW business. It's like if we decided to manage here all dependencies that could be used by TS, how does it make sense to run CI for something we don't use here? We need to raise dependency version in the place where it is used because this way, we will recognize problem with new HTML Unit artifact version on tests.

2023-05-16 11:04 UTC, michalvavrik commented on pom.xml
> -            </dependency>
I'll have a look how HTML Unit is used in TS and come back to you.

2023-05-16 11:05 UTC, michalvavrik commented on pom.xml
> -            </dependency>
before I do - my opinion is that setting is here is not a big deal. The relation between managing dependency here and setting it here is made by you and me. There is none IMHO because it is different to if we were actually using dependency here.

2023-05-16 11:24 UTC, michalvavrik commented on pom.xml
> -            </dependency>
Okay, I had a look. We only need to repeat property in TS 6 times, I suggest to drop it.

2023-05-16 11:36 UTC, michalvavrik commented on pom.xml
> -            </dependency>
Done.

2023-05-16 12:16 UTC, jsmrcka commented on pom.xml
> -            </dependency>
> But whether or not TS decides to manage something, it's not FW business.

I'm not arguing about that.
My point is that we should prepare a PR which adds the management of this dependency in TS and do it rather now than later.
That way we don't forget about it and avoid TS failures because of the missing dependency.

I agree with dropping the property from FW.
It would be nice to be able to set it just once in TS, but I haven't figured out a way how to do it. But 6 times is IMO fine too.

2023-05-16 13:00 UTC, michalvavrik commented on pom.xml
> -            </dependency>
Sure, here you go https://github.com/quarkus-qe/quarkus-test-suite/pull/1226

2023-05-16 13:34 UTC, jsmrcka commented on pom.xml
> -            </dependency>
Thanks. :+1:

2023-05-16 13:36 UTC, merged