Remove OpenShift expose config property as it has been removed from Quarkus
quarkus-qe/quarkus-test-framework pull request #851
Opened 2023-08-06 08:37 UTC by michalvavrik

### Summary

Quarkus doesn't recognize this property and we already set `quarkus.openshift.route.expose`. The `quarkus.kubernetes.expose` is removed totally without replacement for we obviously don't need/use it (tests are running for 5+ months without its replacement and no issue is there).  Kubernetes client should set `quarkus.kubernetes.ingress.expose`, but I won't make there changes as the client needs overall rework and it doesn't work ATM.

Please see https://github.com/quarkusio/quarkus/pull/30977 for more information.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-08-06 08:46 UTC, michalvavrik commented
run tests

2023-08-07 12:49 UTC, gtroitsk commented
OC failures seems related but the change is ok. Let's rerun OC tests to make sure

2023-08-07 12:51 UTC, gtroitsk commented
run tests

2023-08-09 08:45 UTC, gtroitsk requested changes

2023-08-09 08:45 UTC, gtroitsk commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/ExtensionOpenShiftQuarkusApplicationManagedResource.java
> -    private static final String QUARKUS_PLUGIN_DEPLOY = "-Dquarkus.kubernetes.deploy=true";
We need to leave it, please see https://quarkus.io/guides/deploying-to-openshift#build-and-deployment

2023-08-09 10:17 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/ExtensionOpenShiftQuarkusApplicationManagedResource.java
> -    private static final String QUARKUS_PLUGIN_DEPLOY = "-Dquarkus.kubernetes.deploy=true";
Good catch, I though I was removing `quarkus.kubernetes.expose` and didn't read it correctly, thanks.

2023-08-09 10:43 UTC, michalvavrik commented
run tests

2023-08-09 12:52 UTC, gtroitsk commented
OpenShift test failure is unrelated and was fixed by https://github.com/quarkus-qe/quarkus-test-framework/pull/852

2023-08-09 12:55 UTC, gtroitsk approved these changes

2023-08-09 12:56 UTC, merged