Disable QuarkusScenario tests automatically when Linux containers are not available but the test requires them
quarkus-qe/quarkus-test-framework pull request #864
Opened 2023-08-25 13:43 UTC by michalvavrik

### Summary

tests are automatically disabled when Linux containers are not available,  but the test has a field with the `Container` annotation, or is a (Remote)DevMode test or is QuarkusCli test. The CLI test should be possible to run on Windows in cases when it is not a DEV mode. I'll open issue in the FW for this (good first issue). In TS, CLI tests are disabled on Windows anyway, this way, we will at least test them with RHBQ.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-08-25 14:24 UTC, mjurc reviewed
The change makes sense and the conditions are correct, as far as I can see from the review.

Can we have some runs with test suite on baremetal with docker/podman, too? Perhaps it would be for the better to try this on OCP jobs also.

2023-08-25 14:24 UTC, mjurc commented on quarkus-test-containers/src/main/java/io/quarkus/test/services/execution/conditions/EnableOnLinuxContainersWhenContainersRequiredCondition.java
> +            new Command("docker", "info", "--format", "'{{.OSType}}'")
I'd presume that podman returns the same response, correct? Just to make sure.

Maybe it would be nice to run the test suite on podman too.

2023-08-26 09:10 UTC, michalvavrik commented
run tests

2023-08-28 13:03 UTC, mjurc commented on quarkus-test-core/src/main/java/io/quarkus/test/scenarios/execution/condition/AbstractQuarkusScenarioContainerExecutionCondition.java
> +            new Command("docker", "info", "--format", "'{{.OSType}}'")
I think `{{.OSType}}` is not present on podman - I tried `podman info` locally without any such line being provided. 

I think the podman failures in CI are caused by that.

2023-08-28 15:35 UTC, mjurc requested changes
Actually I think my last review comment will require changes.

2023-08-28 21:04 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/scenarios/execution/condition/AbstractQuarkusScenarioContainerExecutionCondition.java
> +            new Command("docker", "info", "--format", "'{{.OSType}}'")
> I think {{.OSType}} is not present on podman - I tried podman info locally without any such line being provided.

I see, I based my input on stuff from Podman on Windows, either it differs or I misunderstood the info.

> I think the podman failures in CI are caused by that.

sure

> Mind you - https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/java/io/quarkus/test/utils/Command.java#L72 throws runtime exception in case the return value of launched command is non-zero, which I think could be an issue for this as well - as runtime exceptions are notoriously hard to catch. This will result in exception rather than skipped test.

Not sure why we couldn't catch `RuntimeException`, I'm probably missing something, but anyway, exception handling is expensive and I would rather avoid it. I checked how Quarkus implements it `io.quarkus.runtime.util.ContainerRuntimeUtil#detectContainerRuntime(boolean)` and it doesn't feel nor efficient or suitable for our case. I suggest to check `DOCKER_HOST` which should do on Linux (and is quicker then executing command) then check docker version for `podman` keyword then do the same info command. It's one more command then I'd like, but I couldn't figure how to use `missingkey` in Go templates nor how to convince JSON format to don't complain about missing key.

I tested it on Podman instance manually, but will re-trigger Podman job as well. Thanks for fixing it.

2023-08-28 21:13 UTC, michalvavrik commented
run tests

2023-08-29 08:16 UTC, mjurc commented
run tests

2023-08-29 08:32 UTC, mjurc approved these changes
Thanks. Think this looks fine now, although that `catch (Exception ex)` is kinda nasty.

Let's get the CI run green - it seems that the test clusters had full objectstore after last week.

2023-08-29 10:07 UTC, michalvavrik commented
All green, merging, thanks for the review.

2023-08-29 10:07 UTC, merged