Remove rollout from deployment
quarkus-qe/quarkus-test-framework pull request #889
Opened 2023-09-26 14:57 UTC by fedinskiy

### Summary

Rollout is only used for deployment via container registry, but tests are working fine even without it. At the same time, it often causes hard-to-reproduce bugs, with "Failure executing: PATCH at: <...>the object has been modified" exception

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-09-26 15:10 UTC, fedinskiy commented
run tests

2023-09-26 16:25 UTC, mjurc approved these changes
It really does seem extraneous, good catch, as the `doInit` waits for the service.

Let's see what the CI says.

2023-09-26 16:49 UTC, mjurc requested changes
It seems like the rollout wasn't all that redundant after all - can you look at the CI failures? All of the tests that failed use the resource managed by this deployment strategy.

2023-09-27 09:21 UTC, fedinskiy commented
@mjurc we run nightly with `999-SNAPSHOT` (and the fix works with it), but we run CI with 3.2.5.Final (and the fix fails there as well as in 3.4.1).

I am not sure if this behavior of fabirc8 constitutes a bug, though

2023-09-28 20:48 UTC, mjurc commented
Let's hold off merging this in until after we branch out for 3.2 and we update to Quarkus with that version in the main, then.

2023-10-05 10:13 UTC, fedinskiy commented
3.4.2 is still bugged

2023-10-17 15:46 UTC, michalvavrik commented
run tests

2023-10-17 15:53 UTC, michalvavrik commented
run tests

2023-10-17 16:00 UTC, michalvavrik commented
run tests

2023-10-17 18:22 UTC, michalvavrik approved these changes
There are only 2 failures left, I think they are related and I'm going to investigate them separately because this PR is already fixing tests and we need to move with this. Thanks for contribution. We will definitely need to check TS as well before we proceed with release. I'm going to take care of it.

2023-10-17 18:23 UTC, michalvavrik commented
I need to bump Quarkus version because it is very much related.

2023-10-17 18:23 UTC, michalvavrik commented
JVM failure fixed here https://github.com/quarkus-qe/quarkus-test-framework/pull/912.

2023-10-17 18:23 UTC, merged

2023-10-17 19:51 UTC, michalvavrik commented
One of OC tests fixed here https://github.com/quarkus-qe/quarkus-test-framework/pull/915, I'll debug the other one tomorrow.