Enable to use java preview while executing built jar file.
quarkus-qe/quarkus-test-framework pull request #893
Opened 2023-10-02 17:08 UTC by jedla97

### Summary

Hi, this PR adding option run built jar with preview argument. This can be useful when someone trying the JEPs which are marked as preview. What I tried when using framework with quarkus dev mode it pass the property `-D--enable-preview` but when using standard mode the property is not picked so jar failing to execute.

Running `mvn -B -fae clean install -Pframework,examples -Dvalidate-format -Dquarkus.platform.version="999-SNAPSHOT" -pl examples/database-mysql -D--enable-preview `

Before this PR result in produced command `java -D<some Quarkus properties> -jar quarkus-test-framework/examples/database-mysql/target/quarkus-app/quarkus-run.jar`

After this PR result in produced command `java --enable-preview -D<some Quarkus properties> -jar quarkus-test-framework/examples/database-mysql/target/quarkus-app/quarkus-run.jar`

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-10-02 17:41 UTC, michalvavrik requested changes
There is one thing I don't understand - if we only enable preview feature with system properties, how are tests going to pass if the feature is not enabled. I support your main objective is https://github.com/quarkus-qe/quarkus-jdkspecifics/tree/main ? I wonder if it is really desirable to add preview specific tests, we have enough on our plate with testing of what is actually in JDK. If this is only for your personal testing, can't you instead execute it manually, e.g. package and then run it as any other app? 

It's possible I'm missing something, please let me know.

2023-10-02 17:41 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +                command.add("--enable-preview");
pls make `--enable-preview` constant

2023-10-02 17:41 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +    private boolean isEnabledPreview() {
this method can be static

2023-10-02 17:41 UTC, michalvavrik commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +        String enablePreviewString = System.getProperty("--enable-preview");
I don't have strong opinion here, but if this is something specific for this framework. it should be framework config property. Therefore instead of `-D--enable-preview ` create property like `ts.enable-java-preview-features` (please name it yourself) and use `PropertyLookup` and document it when this get merged in Wiki.

Let's here from others though, this is just my preference.

2023-10-02 19:45 UTC, rsvoboda requested changes
This feature is specific for baremetal use case in prod mode / when application is started using `java -jar`.
It's OK-ish, we do not have a need for this in Kube/OpenShift environment or CLI / DEV mode at this moment.

We could consider more generic approach to allow definition of java command arguments, but could be a bit problematic for Kube/OpenShift and dev mode.

2023-10-02 19:45 UTC, rsvoboda commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +        String enablePreviewString = System.getProperty("--enable-preview");
+1 for something like `ts.enable-java-preview-features` instead of `-D--enable-preview`

Should be documented in https://github.com/quarkus-qe/quarkus-test-framework/wiki/2.-Configuration once merged.

2023-10-02 20:36 UTC, mjurc reviewed
Generally, I agree with points made by @rsvoboda . I don't mind having it here, but maybe a more general approach could be used.

2023-10-04 13:24 UTC, jedla97 commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +                command.add("--enable-preview");
Updated

2023-10-04 13:26 UTC, jedla97 commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +        String enablePreviewString = System.getProperty("--enable-preview");
I play with it little and change it to the framework property.

2023-10-04 13:26 UTC, jedla97 commented on quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdLocalhostQuarkusApplicationManagedResource.java
> +    private boolean isEnabledPreview() {
Removed as I using the `PropertyLookup` so this method is no longer needed

2023-10-04 13:40 UTC, jedla97 commented
I play with this a little. At first I was thought that without `-D--enable-preview` the devmode won't be working and fail when running the test containing some preview feature. In my surprise there was no problem running it as it probably can take `--enable-preview` set in pom (this case in jdkSpecific TS).

Generally as this probably only quarkus-qe use case the framework property is better, but as just user who can possibly run it everywhere I would prefer `-D--enable-preview` as it propagated to all usecases/enviroments and it's defined in Java. Just my POV after thinking about it.

2023-10-04 14:56 UTC, michalvavrik commented
> I play with this a little. At first I was thought that without `-D--enable-preview` the devmode won't be working and fail when running the test containing some preview feature. In my surprise there was no problem running it as it probably can take `--enable-preview` set in pom (this case in jdkSpecific TS).
> 
> Generally as this probably only quarkus-qe use case the framework property is better, but as just user who can possibly run it everywhere I would prefer `-D--enable-preview` as it propagated to all usecases/enviroments and it's defined in Java. Just my POV after thinking about it.

I'll leave review to others as said, but if you want something propagated to all usecase/environments, can't you use `JDK_JAVA_OPTIONS` set in failsafe plugin? I take it we also need it during build so that is probably the issue, I won't dig into it...

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>${failsafe-plugin.version}</version>
    <configuration>
        <environmentVariables>
            <JDK_JAVA_OPTIONS>--enable-preview</JDK_JAVA_OPTIONS>
        </environmentVariables>
    </configuration>
</plugin>
```

2023-10-04 15:38 UTC, jedla97 commented
> can't you use JDK_JAVA_OPTIONS set in failsafe plugin?

Basically yes in jdk-specific `--enable-preview` it set on multiple places as part of `compilerArgs`, `jvmArgs` or `argLine` and the locally it's used and executed without problem. Not tested it with Kube/OpenShift.

2023-10-09 08:49 UTC, rsvoboda approved these changes

2023-10-09 09:05 UTC, mjurc approved these changes

2023-10-09 09:05 UTC, merged