Migrate from URL to URI constructor
quarkus-qe/quarkus-test-framework pull request #903
Opened 2023-10-12 09:46 UTC by jedla97

…ecated.

### Summary

Hi, this PR updating some deprecated method. To be prepared to JDK 21.

URL constructors was deprecated in JDK 20. Now is possible to create URL from URI.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-10-12 09:46 UTC, jedla97 commented
run tests

2023-10-13 12:20 UTC, jsmrcka requested changes
A minor detail to be fixed, otherwise looks good.

2023-10-13 12:20 UTC, jsmrcka commented on quarkus-test-helm/src/main/java/io/quarkus/test/bootstrap/QuarkusHelmClient.java
> +                    HttpURLConnection con = (HttpURLConnection) url.toURL().openConnection();
```suggestion
                    URI uri = URI.create(fullReadinessPath);
                    HttpURLConnection con = (HttpURLConnection) uri.toURL().openConnection();
```

2023-10-15 21:31 UTC, jedla97 commented on quarkus-test-helm/src/main/java/io/quarkus/test/bootstrap/QuarkusHelmClient.java
> +                    HttpURLConnection con = (HttpURLConnection) url.toURL().openConnection();
Updated

2023-10-16 06:54 UTC, jedla97 commented
The error seems to appear in daily so not PR related

2023-10-16 10:46 UTC, jsmrcka approved these changes
Thanks for the update. The PR failures are indeed unrelated. I am merging this.

2023-10-16 10:47 UTC, merged