Transform non-quarkus config properties to OpenShift environment variables using underscore for non-alphanumeric chars
quarkus-qe/quarkus-test-framework pull request #917
Opened 2023-10-18 11:41 UTC by michalvavrik

### Summary

TODO

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-10-18 11:41 UTC, michalvavrik commented
run tests

2023-10-18 12:28 UTC, michalvavrik commented
run tests

2023-10-18 12:58 UTC, fedinskiy requested changes

2023-10-18 13:03 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +     * Converts names of environment variables to the MicroProfile Config specification compliant format,
SmallRye Config converts stuff from env to config properties, not back, so IMHO no reusing possible.

2023-10-18 13:08 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        final boolean isQuarkusRuntime = dc.getSpec().getTemplate().getMetadata() != null
> but this method converts all the properties
exactly, so there is no need to check each property individually(as we did before) -> instead of checking, if the method should do something or not, we can check if we need to call it or not

2023-10-18 13:09 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        final boolean isQuarkusRuntime = dc.getSpec().getTemplate().getMetadata() != null
IMO done

2023-10-18 13:11 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +     * Converts names of environment variables to the MicroProfile Config specification compliant format,
javadocs fixed; I don't see just util in SmallRye Config project

2023-10-18 13:12 UTC, fedinskiy requested changes

2023-10-18 13:12 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +    private static Map<String, String> convertPropertiesToEnvironment(Map<String, String> properties, DeploymentConfig dc) {
No need to pass deployment config anymore

2023-10-18 13:12 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                if (isQuarkusRuntime) {
The question about other runtimes still lingers.

2023-10-18 13:19 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +     * Converts names of environment variables to the MicroProfile Config specification compliant format,
`io.smallrye.config.common.utils.StringUtil#replaceNonAlphanumericByUnderscores` is not available for us

2023-10-18 13:20 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +    private static Map<String, String> convertPropertiesToEnvironment(Map<String, String> properties, DeploymentConfig dc) {
thanks

2023-10-18 13:21 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                if (isQuarkusRuntime) {
but if you mean whether this condition is sometimes false, yes, for non-Quarkus pods like containers with Amq, Keycloak etc.

2023-10-18 13:24 UTC, michalvavrik commented
run tests

2023-10-19 06:54 UTC, michalvavrik commented
I have verified that 2 remaining OCP failures are related to the Quarkus version (`OpenShiftStrimziKafkaWithRegistryMessagingIT`, `OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT`) are reproducable on main as well (not related to this PR), they go down to the Quarkus bump (which fixed more issues). I'll fix them in a separate PR - already working on it.

2023-10-19 06:54 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                if (isQuarkusRuntime) {
@fedinskiy work with me, I'm happy to make changes in order to get it in (I need to update TS this week and fix stuff), but I simply don't understand.

2023-10-19 07:11 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                if (isQuarkusRuntime) {
I wanted to suggest, that we should translate properties for all containers. On the other hand, since results of our current CI are more or less successful, let's keep it as is.

2023-10-19 07:12 UTC, fedinskiy commented
@michalvavrik what's with Github JVM failure?

2023-10-19 07:13 UTC, michalvavrik commented
> @michalvavrik what's with Github JVM failure?

@fedinskiy https://github.com/quarkus-qe/quarkus-test-framework/pull/921, it can't be fixed with a reasonable effort, so I disabled it

2023-10-19 07:17 UTC, fedinskiy approved these changes
Thank you for the fix!

2023-10-19 07:18 UTC, merged