OpenShift environment variables with dashes or other special chars in name must be also present in lower priority dotted config source to be matched
quarkus-qe/quarkus-test-framework pull request #923
Opened 2023-10-19 17:01 UTC by michalvavrik

### Summary

#904 and #917 follow-up

Right now OpenShift tests that has dashes or other non-alphanumeric charcters in property key name (between dots) are not resolved if they are also not present in dotted config source as explain by Quarkus docs https://quarkus.io/version/main/guides/config-reference#environment-variables. This PR adds these properties as Quarkus Application config source and thus helps SR Config to resolve them.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-10-19 18:29 UTC, michalvavrik commented
`OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT` is failing before this PR and it can't have anything to do with this PR. because it fails during Kafka installation and this PR only touches Quarkus deployment configs.

I'm working on it, but it's a separate ongoing issue and this PR fixes what it says - for example `OpenShiftStrimziKafkaWithRegistryMessagingIT`

2023-10-19 18:39 UTC, michalvavrik commented
Ah, so the one failing test is failing because operator doesn't support our Kafka version _Unsupported Kafka.spec.kafka.version: 3.4.0. Supported versions are: [3.5.0, 3.5.1, 3.6.0]_

2023-10-19 19:08 UTC, michalvavrik commented
run test

2023-10-19 20:05 UTC, michalvavrik commented
run tests

2023-10-20 07:06 UTC, fedinskiy requested changes

2023-10-20 07:06 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            String envVarTransformedToDottedConfigPropFormat = StringUtil.toLowerCaseAndDotted(variable);
Using input parameter to store a result (that's what happening here with `propsWithDashOrOtherSpecChar` ) is an antipattern. Please, move generation this set into another method

2023-10-20 07:06 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                .map(propKey -> propKey + "=" + enrichProperties.get(propKey) + "\n")
It seems, that instead of storing filtered keys of property names and properties themselves in a separate structures, we can have a map of filtered properties. That will significantly easy cognitive load.

2023-10-20 07:06 UTC, fedinskiy commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        createOrUpdateConfigMap(appConfigFileName, APP_PROPS_CONFIG_MAP_KEY, appProperties);
This method requires multiline string to work properly?

2023-10-20 07:53 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        createOrUpdateConfigMap(appConfigFileName, APP_PROPS_CONFIG_MAP_KEY, appProperties);
not sure what you mean, application.properties has multiple lines and are you are supposed to specify one property per line. or do you dislike that I store `APP_PROPS_CONFIG_MAP_KEY` as string constant? or do you suggest to not use config map?

2023-10-20 07:54 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            String envVarTransformedToDottedConfigPropFormat = StringUtil.toLowerCaseAndDotted(variable);
it means additional loop, will do

2023-10-20 07:54 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                .map(propKey -> propKey + "=" + enrichProperties.get(propKey) + "\n")
ok

2023-10-20 08:14 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        createOrUpdateConfigMap(appConfigFileName, APP_PROPS_CONFIG_MAP_KEY, appProperties);
this config map key is mounted as volume. configmap format is key: value (etc. you this better than I do, it's yaml). how could I mount many keys as one volume? this one key is key of application.properties file, not one configuration property

2023-10-20 08:57 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +            String envVarTransformedToDottedConfigPropFormat = StringUtil.toLowerCaseAndDotted(variable);
done

2023-10-20 08:57 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                .map(propKey -> propKey + "=" + enrichProperties.get(propKey) + "\n")
it's one string now

2023-10-20 08:58 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +        createOrUpdateConfigMap(appConfigFileName, APP_PROPS_CONFIG_MAP_KEY, appProperties);
I rewrote var name, is it clearer now?

2023-10-20 09:07 UTC, michalvavrik commented
run tests

2023-10-20 11:30 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                    return !configPropertyNameCreatedFromEnvName.equalsIgnoreCase(configPropertyName);
I'm not a logic owner, it means taking over ownership from SmallRye Config. Right now, I'm handing over responsibility over to SR Config, unless I'm using wrong methods. I don't expect specs to change, but I also don't expect that some regex or something will be more effective, because SR Config goes char by char and I think it is more efficient. So I can extract certain parts from their code.

I don't really have stand here, for me, it's small gain vs small risk, WDYT?

2023-10-20 11:44 UTC, michalvavrik commented on quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
> +                    return !configPropertyNameCreatedFromEnvName.equalsIgnoreCase(configPropertyName);
I don't think it's important.

2023-10-20 11:47 UTC, fedinskiy approved these changes

2023-10-20 12:03 UTC, mjurc approved these changes
Thanks for the fix!

2023-10-20 12:03 UTC, merged