Update Kafka utils to use images from Maven properties
quarkus-qe/quarkus-test-framework pull request #976
Opened 2023-12-10 09:22 UTC by gtroitsk

### Summary

KafkaRegistry and KafkaVendor now using image defined in Maven properties. It helps track versions from one place.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-12-10 09:54 UTC, gtroitsk commented
run tests

2023-12-11 08:47 UTC, michalvavrik approved these changes
LGTM

I would prefer to have review of @fedinskiy and @mjurc because this is very opinionated change, but they are out for the rest of this month. Maybe we can wait a little if @rsvoboda find a time to review. 

We can always tweak next month.

2023-12-11 08:49 UTC, michalvavrik requested changes
Ouch, I didn't scroll down, I still agree in principal, but I think all failures are related.

2023-12-11 15:19 UTC, gtroitsk commented
run tests

2023-12-11 21:09 UTC, rsvoboda requested changes
2 small changes requested

I think this is OK-ish, the ask in QQE-41 is for test-suite.

+1 to wait for @mjurc and his opinion

2023-12-11 21:09 UTC, rsvoboda commented on quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/containers/model/KafkaVendor.java
> +    KafkaVendor(String image, int port, KafkaRegistry registry) {
```suggestion
    KafkaVendor(String imagePropertyName, int port, KafkaRegistry registry) {
```

2023-12-11 21:09 UTC, rsvoboda commented on quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/containers/model/KafkaRegistry.java
> +    KafkaRegistry(String image, String path, int port) {
```suggestion
    KafkaRegistry(String imagePropertyName, String path, int port) {
```

2023-12-13 09:55 UTC, michalvavrik approved these changes

2023-12-13 10:16 UTC, rsvoboda approved these changes
Approving, I don't thing we need to wait for MichalJ. This is relatively internal change, people use the enum values and they didn't change.

2023-12-13 10:16 UTC, merged